[MIG][10.0] sql_export
OCA/server-tools pull request #1047
Opened 2017-11-10 15:34 UTC by aheficent

Tasks done:
- Bump code to new version. Minor changes.

No extra features added/removed from v9

2017-11-10 15:35 UTC, aheficent commented
@florian-dacosta @jbeficent

2017-11-13 09:55 UTC, yajo requested changes
code review

2017-11-13 09:55 UTC, Yajo commented on sql_export/demo/sql_export.xml
> +<odoo><data>
Remove `<data>`, not required now.

2017-11-13 09:55 UTC, Yajo commented on sql_export/security/sql_export_security.xml
> +<odoo noupdate="0">
`noupdate="0"` is the default, you can remove that, or use `noupdate="1"`, which is probably what the author wanted in the first place.

2017-11-23 09:54 UTC, florian-dacosta approved these changes
Code review, no test
Just one small not blocking comment

Thanks for the port !

2017-11-23 09:54 UTC, florian-dacosta commented on sql_export/README.rst
> +There are some restrictions in the sql sql request, you can only read datas.
in the sql sql request > in the sql query

2017-11-23 15:46 UTC, aheficent commented
@Yajo would you update your review?

2017-11-30 11:34 UTC, yajo approved these changes
code looks ok, but please squash all translation commits: 
![captura de pantalla de 2017-11-30 12-33-28](https://user-images.githubusercontent.com/973709/33428836-c6d6130c-d5ca-11e7-8445-4f778147b87b.png)

I didn't do a functional test, I'd appreciate one from a real addon user (I don't use this one) to check migration works "Eficent"ly 😋

2018-05-24 10:21 UTC, Abranes commented
Hello,
Tested but not work with parameters.
When I use any parameter to do a dynamic query I get an error:
`TypeError: 'dict' object does not support indexing`
This error come from https://github.com/OCA/server-tools/blob/86c6238433184f1a81f5a53a4c68306ff5697d79/sql_request_abstract/models/sql_request_mixin.py#L148
This function describe that the `params` need to be a `dict` but `mogrify` doesn't accept `dict` as a parameter.

2018-06-14 11:50 UTC, aheficent commented
I will check

2018-06-25 14:46 UTC, aheficent commented
Thank you @mreficent !

2018-06-26 10:14 UTC, MiquelRForgeFlow approved these changes

2018-06-26 10:20 UTC, mreficent commented
@Abranes could you check now if it works fine with paramenters?

2018-06-27 13:54 UTC, merged