11.0 mig mass editing
OCA/server-tools pull request #1048
Opened 2017-11-11 18:29 UTC by jnegrete

2017-11-13 09:50 UTC, yajo requested changes
Could you explain why are you removing all things related to `ir.values`?

Also, squash all translation-related commits together and fix Travis please.

2017-11-13 09:50 UTC, Yajo commented on mass_editing/__manifest__.py
> +        'Juan Negrete <jnegrete@casasalce.com>'
Contributors nowadays go into README, this part can be dropped from here.

2017-11-13 09:50 UTC, Yajo commented on mass_editing/hooks.py
> +        cr.execute("DELETE FROM ir_act_window WHERE id = '%s'" % res.get('id'))
1. Is this needed? Doesn't Odoo by itself automatically remove tables when an addon is uninstalled?
   - Yes: Add a docstring on why.
   - No: remove it.
2. This query is a little bit.... well, not KISS. Just `DELETE FROM ir_act_window WHERE res_model = 'mass.editing.wizard'` and you're done

2017-11-13 09:50 UTC, Yajo commented on mass_editing/wizard/mass_editing_wizard.py
> +            for key, val in list(vals.items()):
why?

2017-11-13 09:50 UTC, Yajo commented on mass_editing/wizard/mass_editing_wizard.py
> +            for field in list(all_fields.values()):
why?

2017-11-13 23:20 UTC, jnegrete commented
Hello Jairo,

ir.values doesn't exist in odoo v11.0

I add the query and remove list, they were added by 2to3 -wnj4 --no-diffs

Regards.

2017-11-13 3:50 GMT-06:00 Jairo Llopis <notifications@github.com>:

> *@Yajo* requested changes on this pull request.
>
> Could you explain why are you removing all things related to ir.values?
> ------------------------------
>
> In mass_editing/__manifest__.py
> <https://github.com/OCA/server-tools/pull/1048#discussion_r150487095>:
>
> >      'author': 'Serpent Consulting Services Pvt. Ltd., '
>                'Tecnativa, '
>                'Odoo Community Association (OCA)',
>      'contributors': [
>          'Oihane Crucelaegui <oihanecrucelaegi@gmail.com>',
>          'Serpent Consulting Services Pvt. Ltd. <support@serpentcs.com>',
> -        'Jay Vora <jay.vora@serpentcs.com>'
> +        'Jay Vora <jay.vora@serpentcs.com>',
> +        'Juan Negrete <jnegrete@casasalce.com>'
>
> Contributors nowadays go into README, this part can be dropped from here.
> ------------------------------
>
> In mass_editing/hooks.py
> <https://github.com/OCA/server-tools/pull/1048#discussion_r150487535>:
>
> > @@ -7,6 +6,5 @@ def uninstall_hook(cr, registry):
>      cr.execute("""SELECT id FROM ir_act_window
>                 WHERE res_model = 'mass.editing.wizard'""")
>      for res in cr.dictfetchall():
> -        value = 'ir.actions.act_window,%s' % res.get('id')
> -        cr.execute("DELETE FROM ir_values WHERE value = %s", (value, ))
> +        cr.execute("DELETE FROM ir_act_window WHERE id = '%s'" % res.get('id'))
>
>
>    1. Is this needed? Doesn't Odoo by itself automatically remove tables
>    when an addon is uninstalled?
>       - Yes: Add a docstring on why.
>       - No: remove it.
>    2. This query is a little bit.... well, not KISS. Just DELETE FROM
>    ir_act_window WHERE res_model = 'mass.editing.wizard' and you're done
>
> ------------------------------
>
> In mass_editing/wizard/mass_editing_wizard.py
> <https://github.com/OCA/server-tools/pull/1048#discussion_r150487938>:
>
> > @@ -238,7 +238,7 @@ def create(self, vals):
>                  self._context.get('active_ids')):
>              model_obj = self.env[self._context.get('active_model')]
>              values = {}
> -            for key, val in vals.items():
> +            for key, val in list(vals.items()):
>
> why?
> ------------------------------
>
> In mass_editing/wizard/mass_editing_wizard.py
> <https://github.com/OCA/server-tools/pull/1048#discussion_r150488009>:
>
> > @@ -208,7 +208,7 @@ def fields_view_get(self, view_id=None, view_type='form', toolbar=False,
>                              'colspan': '4',
>                          })
>              # Patch fields with required extra data
> -            for field in all_fields.values():
> +            for field in list(all_fields.values()):
>
> why?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/OCA/server-tools/pull/1048#pullrequestreview-76041458>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AEhl6q3ymb_wyDkzn7LuvA6DCnbKJhK6ks5s2BD5gaJpZM4QaljY>
> .
>

2017-11-14 09:08 UTC, yajo requested changes

2017-11-14 09:08 UTC, Yajo commented on mass_editing/__manifest__.py
>      'contributors': [
Please remove the key and move contributors to README

2017-11-15 12:42 UTC, CasVissers commented
I ran a functional test everything worked fine untill I tried to edit some values:
`Fout:
TypeError: val is null

https://vitamineenzo.odoo.com/web/content/960-ac050f6/web.assets_backend.js:1245
Traceback:
_parseServerData/<@https://vitamineenzo.odoo.com/web/content/960-ac050f6/web.assets_backend.js:1245:545
_.forEach@https://vitamineenzo.odoo.com/web/content/906-d57f445/web.assets_common.js:12:558
_parseServerData@https://vitamineenzo.odoo.com/web/content/960-ac050f6/web.assets_backend.js:1245:288
_fetchRecord/<@https://vitamineenzo.odoo.com/web/content/960-ac050f6/web.assets_backend.js:1185:81
then/</</<@https://vitamineenzo.odoo.com/web/content/906-d57f445/web.assets_common.js:802:678
fire@https://vitamineenzo.odoo.com/web/content/906-d57f445/web.assets_common.js:796:281
fireWith@https://vitamineenzo.odoo.com/web/content/906-d57f445/web.assets_common.js:801:198
then/</</<@https://vitamineenzo.odoo.com/web/content/906-d57f445/web.assets_common.js:802:849
fire@https://vitamineenzo.odoo.com/web/content/906-d57f445/web.assets_common.js:796:281
fireWith@https://vitamineenzo.odoo.com/web/content/906-d57f445/web.assets_common.js:801:198
Deferred/</deferred[tuple[0]]@https://vitamineenzo.odoo.com/web/content/906-d57f445/web.assets_common.js:803:31
rpc/</<@https://vitamineenzo.odoo.com/web/content/906-d57f445/web.assets_common.js:3858:346
then/</</<@https://vitamineenzo.odoo.com/web/content/906-d57f445/web.assets_common.js:802:678
fire@https://vitamineenzo.odoo.com/web/content/906-d57f445/web.assets_common.js:796:281
fireWith@https://vitamineenzo.odoo.com/web/content/906-d57f445/web.assets_common.js:801:198
Deferred/</deferred[tuple[0]]@https://vitamineenzo.odoo.com/web/content/906-d57f445/web.assets_common.js:803:31
fire@https://vitamineenzo.odoo.com/web/content/906-d57f445/web.assets_common.js:796:281
fireWith@https://vitamineenzo.odoo.com/web/content/906-d57f445/web.assets_common.js:801:198
then/</</<@https://vitamineenzo.odoo.com/web/content/906-d57f445/web.assets_common.js:802:849
fire@https://vitamineenzo.odoo.com/web/content/906-d57f445/web.assets_common.js:796:281
fireWith@https://vitamineenzo.odoo.com/web/content/906-d57f445/web.assets_common.js:801:198
then/</</<@https://vitamineenzo.odoo.com/web/content/906-d57f445/web.assets_common.js:802:849
fire@https://vitamineenzo.odoo.com/web/content/906-d57f445/web.assets_common.js:796:281
fireWith@https://vitamineenzo.odoo.com/web/content/906-d57f445/web.assets_common.js:801:198
done@https://vitamineenzo.odoo.com/web/content/906-d57f445/web.assets_common.js:1192:86
callback@https://vitamineenzo.odoo.com/web/content/906-d57f445/web.assets_common.js:1212:15`

2017-11-15 23:11 UTC, jnegrete commented
Hi Cas Vissers,

Encontré un problema con los campos computados (like standard_price), puede
ser tu caso, prueba con el nuevo cambio

2017-11-15 6:42 GMT-06:00 Cas Vissers <notifications@github.com>:

> I ran a functional test everything worked fine untill I tried to edit some
> values:
> `Fout:
> TypeError: val is null
>
> https://vitamineenzo.odoo.com/web/content/960-ac050f6/web.
> assets_backend.js:1245
> Traceback:
> _parseServerData/<@https://vitamineenzo.odoo.com/web/
> content/960-ac050f6/web.assets_backend.js:1245:545
> _.forEach@https://vitamineenzo.odoo.com/web/content/906-d57f445/web.
> assets_common.js:12:558
> _parseServerData@https://vitamineenzo.odoo.com/web/
> content/960-ac050f6/web.assets_backend.js:1245:288
> _fetchRecord/<@https://vitamineenzo.odoo.com/web/content/960-ac050f6/web.
> assets_backend.js:1185:81
> then/</</<@https://vitamineenzo.odoo.com/web/content/906-d57f445/web.
> assets_common.js:802:678
> fire@https://vitamineenzo.odoo.com/web/content/906-
> d57f445/web.assets_common.js:796:281
> fireWith@https://vitamineenzo.odoo.com/web/content/906-
> d57f445/web.assets_common.js:801:198
> then/</</<@https://vitamineenzo.odoo.com/web/content/906-d57f445/web.
> assets_common.js:802:849
> fire@https://vitamineenzo.odoo.com/web/content/906-
> d57f445/web.assets_common.js:796:281
> fireWith@https://vitamineenzo.odoo.com/web/content/906-
> d57f445/web.assets_common.js:801:198
> Deferred/</deferred[tuple[0]]@https://vitamineenzo.odoo.com/
> web/content/906-d57f445/web.assets_common.js:803:31
> rpc/</<@https://vitamineenzo.odoo.com/web/content/906-
> d57f445/web.assets_common.js:3858:346
> then/</</<@https://vitamineenzo.odoo.com/web/content/906-d57f445/web.
> assets_common.js:802:678
> fire@https://vitamineenzo.odoo.com/web/content/906-
> d57f445/web.assets_common.js:796:281
> fireWith@https://vitamineenzo.odoo.com/web/content/906-
> d57f445/web.assets_common.js:801:198
> Deferred/</deferred[tuple[0]]@https://vitamineenzo.odoo.com/
> web/content/906-d57f445/web.assets_common.js:803:31
> fire@https://vitamineenzo.odoo.com/web/content/906-
> d57f445/web.assets_common.js:796:281
> fireWith@https://vitamineenzo.odoo.com/web/content/906-
> d57f445/web.assets_common.js:801:198
> then/</</<@https://vitamineenzo.odoo.com/web/content/906-d57f445/web.
> assets_common.js:802:849
> fire@https://vitamineenzo.odoo.com/web/content/906-
> d57f445/web.assets_common.js:796:281
> fireWith@https://vitamineenzo.odoo.com/web/content/906-
> d57f445/web.assets_common.js:801:198
> then/</</<@https://vitamineenzo.odoo.com/web/content/906-d57f445/web.
> assets_common.js:802:849
> fire@https://vitamineenzo.odoo.com/web/content/906-
> d57f445/web.assets_common.js:796:281
> fireWith@https://vitamineenzo.odoo.com/web/content/906-
> d57f445/web.assets_common.js:801:198
> done@https://vitamineenzo.odoo.com/web/content/906-
> d57f445/web.assets_common.js:1192:86
> callback@https://vitamineenzo.odoo.com/web/content/906-
> d57f445/web.assets_common.js:1212:15`
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/OCA/server-tools/pull/1048#issuecomment-344580895>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AEhl6tZh8yPnz1ZLYeHVspfnH3bvN1Eaks5s2twlgaJpZM4QaljY>
> .
>

2017-11-16 08:05 UTC, Yajo commented
Please remove cd3c87e, it was better before. If any computed method fails with that, it should be fixed in the computed method, not there.

OTOH, @CasVissers' logs are JS logs, not Python logs, so there's a high chance that the problem is in the client side.

As always, those logs are not in `?debug=assets` mode, so they are almost completely useless. Can you switch to that mode and paste the good logs please @CasVissers?

2017-11-17 10:45 UTC, RoelAdriaans-B-informed commented
Shoudn't this be moved to https://github.com/OCA/server-ux/ as per https://docs.google.com/spreadsheets/d/1Xg95cW4TFMf_Lo5i_CZC_qOOfN8RgxPRc0LJTLTkdUI/edit?usp=sharing ( From issue #1008 )

2017-11-17 10:47 UTC, pedrobaeza commented
Yeah!

2017-11-17 10:55 UTC, Yajo commented
True, closing. Reopen there please.

2017-11-17 10:55 UTC, closed without merging