11.0 mig server environment ir config parameter
OCA/server-tools pull request #1058
Opened 2017-11-16 10:09 UTC by TDu

2017-11-16 10:15 UTC, yajo requested changes
Just on little detail.

2017-11-16 10:15 UTC, Yajo commented on server_environment_ir_config_parameter/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/149/10.0
11.0

2017-11-16 12:05 UTC, TDu commented on server_environment_ir_config_parameter/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/149/10.0
Done

2017-11-17 07:20 UTC, Yajo commented
Bots are ❌

2017-11-17 07:39 UTC, TDu commented
About the red test, seems that the package python-mysqldb [in travis.yml](https://github.com/OCA/server-tools/blob/ea9b0d58fcadc7792a9b4f570b32a947c7d5ffcf/.travis.yml#L16) does not support Python 3

2017-11-17 07:41 UTC, Yajo commented
Then please take the chance to remove it.

2017-11-17 14:17 UTC, TDu commented
Waiting for [server_environment to be migrated](https://github.com/OCA/server-tools/pull/1051)

2017-11-24 08:23 UTC, grindtildeath approved these changes
Tested with https://github.com/OCA/server-tools/pull/1051 and works well :+1:

2017-11-29 10:28 UTC, simahawk commented
@TDu can you rebase and add the oca_dependencies to include #1051 until is merged?

2017-11-29 10:31 UTC, simahawk requested changes
LGTM, just include #1051 to make travis happy :)

2017-11-30 12:17 UTC, TDu commented
I added oca_dependencies.txt
But server_environment depends on server_environment_files. I changed .travis.yml to create it like on branch 10.0 but still not working...

2018-01-16 17:31 UTC, pedrobaeza commented
Close in favor of https://github.com/OCA/server-env/pull/8

2018-01-16 17:31 UTC, closed without merging