[9.0][kpi] FIX #1093
OCA/server-tools pull request #1095
Opened 2017-12-13 18:08 UTC by ivantodorovich

This should FIX #1093 and added a few minor improvements

2017-12-13 18:34 UTC, ivantodorovich commented
As I understand, commits are automatically squashed before merging, right?
Otherwise, please let me know so I squash them first.

2017-12-13 22:03 UTC, max3903 requested changes
Minor change otherwise LGTM

:+1:

2017-12-13 22:03 UTC, max3903 commented on kpi/__openerp__.py
> +    "version": "9.0.2.0.0",
@ivantodorovich A module upgrade is enough here, so this should be `9.0.1.1.0`.

2017-12-13 22:59 UTC, max3903 approved these changes

2018-04-11 22:08 UTC, ivantodorovich commented
Hi @max3903 !

Do you know anyone else interested in these modules that might be able to review this?
I'd really like to keep working on improving all the mgmtsystem modules, as we use them intensively in our company. Would love to do it on the OCA repositories.

2018-04-11 22:45 UTC, merged

2018-04-11 22:47 UTC, max3903 commented
@ivantodorovich I don't know but 4 months is enough time.

2018-04-12 21:35 UTC, ivantodorovich commented
Thanks!