Add new module: materialized sql view
OCA/server-tools pull request #110
Opened 2015-01-09 17:05 UTC by petrus-v

Hi,

I'm Pierre Verkest from Anybox, I'm pretty new in OCA and not sure about
the workflow to add new modules. Anyway this is a module we developed
on [bitbucket](https://bitbucket.org/anybox/materialized_sql_view).

I'm glad to contribute and dive into OCA tools and thanks @legalsylvain who
ask us to push this `materialized_sql_view` module here.

If you want to know more about this module you can read materialized_sql_view
module description in `__openerp__.py`.

I had to separate tests in an other module as I would tested the module with a
real model but wouldn't see it on production servers.

I already prepare a [branch running under v7](https://github.com/petrus-v/server-tools/tree/7.0-materialized_sql_view)
I guess if it's like odoo workflow I haven't to make a PR on both branches (7.0 and 8.0) ?

I was surprised some tested pass in Travis, like this one:
 https://travis-ci.org/petrus-v/server-tools/builds/46459751 based on this
commit: https://github.com/petrus-v/server-tools/commit/ab614eddd7f11dc81251080960f1969e6454d396
which should failed.

regards,

2015-01-09 20:05 UTC, clonedagain commented on materialized_sql_view/__openerp__.py
> +    'version': '0.0.1',
I think 0.1 would suffice.

2015-01-09 20:36 UTC, clonedagain commented
That looks nice. I wonder if you couldn't simplify the code by dropping the legacy postgresql option. PG 9.3 has been available for quite some time and is the version recommanded by odoo SA.

2015-01-09 22:26 UTC, petrus-v commented
@clonedagain,
Yes it could be easier if we had to support only one PG version, but we made it because we need it for our customer. Unfortunately we don't manage hosting for him, and it can take a while to make a plan with three parts (customer/hoster/IT integrator).

I could say with experience, companies (mainly true bigger they are) are afraid about change when we talk about their tool whose all employees depends so I'm sure I will find PG9.2 on servers for a couple years!

As you can see, if the PG cluster version is upgraded the module take care about it and will drop and recreate the view against the good version.

I hope the effort to maintain multi PG version will be benefit for the community we have also ideas to enhance this module which could explain some choices: 
- PG9.4 which was released in December introduce a new option `CONCURRENTLY` which could be easily introduce in this module by patterns we had chosen. 
- [using different strategies to refresh materialized view](http://tech.jonathangardner.net/wiki/PostgreSQL/Materialized_Views)
- Display on the UI the last refresh date until data was collected
- Provide a dependency refresh engine (in case of some materialized view depend of some other)

Thanks for your review, I already push the version to 0.1 as recommended.

2015-01-10 21:08 UTC, petrus-v commented
I had not seen that @legalsylvain made the issue #101 before asking us by email which is related to this PR.

2015-01-16 17:14 UTC, yvaucher commented on materialized_sql_view/__openerp__.py
> +    'description': """
In v8.0 description can be put in README.rst to be visible both in github and on Odoo

You can find a sample here:
https://github.com/OCA/maintainers-tools/blob/master/template/module/README.rst

2015-01-16 17:15 UTC, yvaucher commented
fr.po is there but pot file is missing

2015-02-02 08:48 UTC, hbrunn commented
@clonedagain current CentOS ships with postgresql 9.2, so I think it's definitely worthwhile to support that. The code looks good to me, after the README.rst issue and the missing pot file is fixed, I think this is good to merge.

2015-02-02 08:53 UTC, legalsylvain commented
:+1: (Code review, No test.)

2015-02-02 09:25 UTC, petrus-v commented
Sorry I'm quite busy actually, sure I will take in consideration your advices. I also have to push a fixe that we figure out using it on production (a use case when it's crash by space missing on the Postgresql temp directory partition ) !

I'll do it this week!

2015-02-02 23:02 UTC, petrus-v commented
My apologies to reviewers I've just realized it's probably not fair to add capabilities (commit cbbdc16) after your reviews on the module.

2015-02-03 08:48 UTC, yvaucher commented on materialized_sql_view/__openerp__.py
> +    'description': """
Thanks for having created README.rst

Now you just need to remove `description` key from `__openerp__.py`

2015-02-03 08:51 UTC, clonedagain commented
@petrus-v I think it's OK to improve before merging, as long as you notify the reviewers. I prefer that than a new PR.

2015-02-03 08:54 UTC, yvaucher commented
Restarted 3rd job of travis. Due to an error when pulling dependencies:

    ImportError: No module named pytz

Not the first time I see this.

2015-02-03 08:56 UTC, yvaucher commented
BTW @petrus-v don't mind squashing those pep8 / pylint commit. That doesn't help much in history.

2015-02-17 11:04 UTC, petrus-v commented
I've just rebase the PR to have a look what's happen!

2015-06-02 15:42 UTC, StefanRijnhart commented
Looks good (no test). Is travis just not completing its job or has it just been restarted?

2015-06-02 16:05 UTC, nbessi commented on materialized_sql_view/__openerp__.py
> +    'author': 'Pierre Verkest',
Please put OCA in the author as second author

2015-06-02 16:08 UTC, nbessi commented on materialized_sql_view/model/abstract_materialized_sql_view.py
> +        """Abstract Method to overwrite in subclass to drop materialized view
I guess we can provide a base implementation here that can be call with super in inherited class

2015-06-02 16:09 UTC, nbessi commented on materialized_sql_view/model/abstract_materialized_sql_view.py
> +    _sql_mat_view_name = ''
Just a matter of taste but I would prefere a None as default value

2015-06-02 16:11 UTC, nbessi commented on materialized_sql_view/model/abstract_materialized_sql_view.py
> +    """
if the property are mandatory we may use the property decorator to raise a explicit message

2015-06-02 16:13 UTC, nbessi commented on materialized_sql_view/model/abstract_materialized_sql_view.py
> +            raise osv.except_osv(u"Properties must be defined in subclass",
It is a technical error you should raise a ValueError not an osv exception

2015-06-02 16:18 UTC, nbessi commented on materialized_sql_view/model/abstract_materialized_sql_view.py
> +        cr.execute("DROP TABLE IF EXISTS %s CASCADE" % (mat_view_name))
Are we sure for the cascading. It seems dangerous

2015-06-02 16:19 UTC, nbessi commented on materialized_sql_view/model/materialized_sql_view.py
> +class MaterializedSqlView(osv.Model):
Please use new API for new addons

2015-06-02 16:20 UTC, nbessi commented on materialized_sql_view/model/abstract_materialized_sql_view.py
> +class AbstractMaterializedSqlView(osv.AbstractModel):
Please use new API for new addon

2015-06-02 16:21 UTC, nbessi commented on materialized_sql_view/model/abstract_materialized_sql_view.py
> +                   dict(mat_view_name=mat_view_name,
why this syntax is it faster than {} constructor?

2015-06-02 16:24 UTC, nbessi commented on materialized_sql_view/model/materialized_sql_view.py
> +        uid = context.get('delegate_user', uid)
I missed something here what is the use of delegate_user

2015-06-13 08:21 UTC, petrus-v commented
I created PR #174 as this module was formerly develop against version 7.0, I'm still working on moving to the new API!

2015-08-24 07:59 UTC, guewen commented
Looks great!
@petrus-v  Would you agree if we add an option to choose between a view and a materialized view? (then should the module have a more generic name?)

2015-09-01 12:52 UTC, petrus-v commented
Hi @guewen,

If I understand you want to let admin to choose if the sql view is materialized at run time? It could be useful! :+1: 

So how should rename the module ? ``base_sql_view``, ``advanced_sql_view``, ... ?

Still some work to do here... I Just push what I started at Odoo Experiences, thanks again to @nbessi reviews... I know it's still not working but I want to make sure to not lost this work. I plan to carry on next PyCon meeting in october.

regards

2015-09-01 12:57 UTC, guewen commented
@petrus-v I worked on an independent implementation in the meantime: https://github.com/OCA/server-tools/pull/245

2015-09-01 13:07 UTC, petrus-v commented
@guewen it looks useful for customers, I catch your interest to add that option!

2015-09-24 15:19 UTC, legalsylvain commented
Hi @petrus-v, 
Last year I realized a custom module that implement materialized view for V7.0 serie. [see module](https://github.com/grap/odoo-addons-misc/blob/7.0/pos_sale_reporting/model/materialized_model.py)
I'm currently working on porting all my modules in V8.0. I'd like to use 'standard' / 'community' module for that feature.
How can I help you to finish this PR ?

kind regards.

2015-09-24 16:15 UTC, petrus-v commented
Hi @legalsylvain,

Sorry about being so slow on that! Do not hesitate to get that branch and fix it! 

Otherwise If you aren't hurry, I though to carry on this project at OCA code sprint at [PynConFr](http://www.pycon.fr/2015/) in october. Are you comming ?

Can you let me know if you do it, or any one else who want to do it?

2016-01-21 20:18 UTC, codingforfun commented on materialized_sql_view/model/materialized_sql_view.py
> +        if context.get('ascyn', True):
Typo: I think you mean 'async' here.

2016-04-07 05:34 UTC, gurneyalex commented
@petrus-v looks nice. Could you check the crash in the cron on runbot? 

```
Programming error: can't adapt type 'ir.model', in query  SELECT "ir_model"."state","ir_model"."create_date","ir_model"."avoid_quick_create","ir_model"."info","ir_model"."id","ir_model"."model","ir_model"."write_uid","ir_model"."name","ir_model"."create_uid","ir_model"."write_date" FROM "ir_model"
                        WHERE "ir_model".id IN %s  ORDER BY "ir_model"."model"  
```

2016-04-07 15:38 UTC, laetitia-gangloff commented
Hello @petrus-v ,
I start to use this module in V8 after success with V7. And it seems materialized view is always recomputed :( And I am sure this time this is an unicode materialized view.

@gurneyalex I get this error too, so I replace the line 77 from file `materialized_sql_view/model/materialized_sql_view.py` by `model = matview.model_id.model`
I will propose PR to @petrus-v with this change.

2016-04-07 16:08 UTC, petrus-v commented
@laetitia-gangloff , thanks for the PR!

As far as I know we are not using this module on V8... The work still in progress and I'm very slow, sorry about that!

If someone want to carry on this migration, feel free to do it!

2016-04-11 14:17 UTC, Cedric-Pigeon commented
Hi, I tried to use the refresh button of the materialized view.

The view seemed to be refreshed but the state of the view didn't change and stayed on "Refreshing"

2016-10-12 14:01 UTC, Cedric-Pigeon commented
@petrus-v Do you plan to finish this PR ? Thanks.

2016-10-12 14:29 UTC, petrus-v commented
@Cedric-Pigeon I've done some works last code sprint!

I'm gonna push it right now, helps is welcome however! Today I only use version 7!

2017-05-20 13:30 UTC, gurneyalex requested changes
could you fix the two small issues and rebase the PR?

2017-05-20 13:30 UTC, gurneyalex commented on test_materialized_sql_view/tests/test_abstract_materialized_sql_view.py
> +            self.demo_matview_mdl.sql_view_definition
use 
```
sql = self.demo_matview_mdl.sql_view_definition
```

2017-05-20 13:30 UTC, gurneyalex commented on test_materialized_sql_view/tests/test_abstract_materialized_sql_view.py
> +        self.demo_matview_mdl = self.env['test.materialized.view'].with_context(
line too long (79 char max)

2018-04-28 22:53 UTC, pedrobaeza commented
This has been stalled for a long time. It's an interesting idea, but it seems unfinished. If someone wants to revive this, please open a new PR.

2018-04-28 22:53 UTC, closed without merging

2018-05-13 11:58 UTC, legalsylvain commented
materialized view can now be generated by bi_sql_editor OCA modules.