[10.0] [MIG] base custom info
OCA/server-tools pull request #1115
Opened 2017-12-30 18:10 UTC by fanha99

2018-01-01 15:27 UTC, pedrobaeza commented
Please check Travis status

2018-01-02 12:29 UTC, fanha99 commented
hi,
I got this info from the travis:

> FAIL: test_cookie_as_string (odoo.addons.sentry.tests.test_logutils.TestOdooCookieSanitizer)
Traceback (most recent call last):
`   File "/home/travis/build/OCA/server-tools/sentry/tests/test_logutils.py", line 35, in test_cookie_as_string
`     m=proc.MASK,
` AssertionError: 'website_lang=en_us;session_id=hello;Session_ID=hello;foo=bar' != 'website_lang=en_us;session_id=********;Session_ID=********;foo=bar'
FAIL: test_cookie_header (odoo.addons.sentry.tests.test_logutils.TestOdooCookieSanitizer)
Traceback (most recent call last):
`   File "/home/travis/build/OCA/server-tools/sentry/tests/test_logutils.py", line 78, in test_cookie_header
`     'a_session_id_here={m}'.format(m=proc.MASK))
` AssertionError: 'foo=bar;session_id=hello;Session_ID=hello;a_session_id_here=hello' != 'foo=bar;session_id=********;Session_ID=********;a_session_id_here=********'
FAILED
Module sentry: 2 failures, 0 errors

Any Idea how to fix?

2018-01-30 14:01 UTC, Yajo commented
Wouldn't it be better to leave all as LGPL for an addon such as this one? 🤔

2018-01-30 14:03 UTC, pedrobaeza commented
Module is LGPL already, but I think we missed to change manifest key.

2018-01-30 14:53 UTC, fanha99 commented
Hi all, in this example of readme: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0
There is AGPL. There module in version 10 is LGPL. 
Am I need to switch back to LGPL?

2018-01-30 14:55 UTC, pedrobaeza commented
I think so

2018-01-30 15:37 UTC, fanha99 commented
Hi all, switch back to LGPL as v9.
please help to review.

2018-01-30 15:39 UTC, fanha99 commented
@Yajo : I'm working this module for v11.
I got the same problem: "When you choose a template from the partner form, it fills the values, but properties remain empty" is there any hint to fix it?

2018-01-31 08:17 UTC, Yajo commented
@fanha99 I remember problems with onchange implementation. It was supposedly fixed in Odoo itself, although in the mean time we managed to get a workaround. Read from https://github.com/OCA/server-tools/pull/492#issuecomment-237594285 onwards, all I can say to you must be there.

OTOH, it's easier to discuss on the v11 PR, with runbot & so on. Let's focus on finishing this one and then you can open the v11 and we can chat on that if you like.

2018-01-31 08:18 UTC, yajo approved these changes

2018-03-15 10:56 UTC, leemannd requested changes
A few nitpicking, but averall work looks good to me.
Thanks!

2018-03-15 10:56 UTC, leemannd commented on base_custom_info/__manifest__.py
> +    'website': 'https://www.tecnativa.com',
https://github.com/OCA/maintainer-tools/blob/master/template/module/__openerp__.py#L9

2018-03-15 10:56 UTC, leemannd commented on base_custom_info/__init__.py
>  # © 2015 Antiun Ingeniería S.L. - Sergio Teruel
all s/©/Copyright/

2018-03-15 11:22 UTC, TelmoSenseFly commented on base_custom_info/models/custom_info_property.py
> +    @api.one
Isn't the deprecation of ```api.one``` after version ` ``9.0``` in place?
https://www.odoo.com/documentation/10.0/reference/orm.html#module-odoo.api

2018-03-15 16:04 UTC, leemannd commented
@TelmoSenseFly Not sure it can be merged now. We have internal testing coming tomorrow.
Do you want the release to be done without it, or shall we wait for tomorrow?

2018-03-15 16:08 UTC, TelmoSenseFly commented
@leemannd No worries. It will be fine to wait for tomorrow.

2018-04-14 07:00 UTC, fanha99 commented
hi @leemannd , @TelmoSenseFly, could you please review again? thx.

2018-11-09 14:44 UTC, diggy128 commented
Could this be merged?

2018-11-09 14:45 UTC, pedrobaeza commented
I think this doesn't contain latest changes in v9.

2018-11-09 14:57 UTC, diggy128 commented
OK. Since I use this module along with other that depend on it, should I try to migrate it from after a rebase?

2018-11-09 14:59 UTC, pedrobaeza commented
OK

2018-11-09 15:15 UTC, leemannd approved these changes

2018-11-21 08:42 UTC, fanha99 commented
> 
> 
> I think this doesn't contain latest changes in v9.

could you please tell me which changes is it?

2018-11-21 08:45 UTC, pedrobaeza commented
@fanha99 sorry, they are there. Please squash your 2 migration commits and I'll merge.

2018-11-21 10:06 UTC, fanha99 commented
@pedrobaeza : done

2018-11-21 11:10 UTC, merged