[11.0] Sentry: Enable setting a release option directly
OCA/server-tools pull request #1127
Opened 2018-01-12 12:00 UTC by aisopuro

sentry: It is not always possible to read commit information from
a production environment. In those cases it is useful to be able
to set a release version manually.

2018-04-24 07:48 UTC, hparfr requested changes
LGTM. Please increment version number of the module :)

2018-04-24 10:15 UTC, aisopuro commented
I updated the minor version number @hparfr

2018-04-24 10:17 UTC, mlaitinen approved these changes
LGTM

2018-04-24 10:18 UTC, hparfr approved these changes

2018-06-05 06:24 UTC, aisopuro commented
Hi @hparfr . Do you still need me to fix something with this PR? Can I do something to help it get merged?

2018-06-05 08:16 UTC, hparfr commented
I already approve it.
You can ping someone with merge rights like @pedrobaeza

2018-08-10 14:33 UTC, aisopuro commented
@pedrobaeza would it be possible to merge this? Is something still needed?

2018-08-10 17:50 UTC, merged

2018-08-10 17:50 UTC, pedrobaeza commented
Yes, thanks for the ping.