[11.0][MIG] html_text
OCA/server-tools pull request #1154
Opened 2018-02-14 12:18 UTC by tarteo

2018-02-19 11:53 UTC, yajo requested changes
Please include https://github.com/OCA/server-tools/pull/1149/files

2018-02-20 09:00 UTC, yajo approved these changes

2018-02-20 10:06 UTC, pedrobaeza commented
Please squash "OCA Transbot" commits together.

2018-03-09 12:19 UTC, tarteo commented
@pedrobaeza squashed them

2018-03-09 13:01 UTC, pedrobaeza commented
I still see 4 commits for v11

2018-03-09 15:52 UTC, tarteo commented
@pedrobaeza Ah the migration commits ;)

2018-03-09 15:55 UTC, pedrobaeza commented
Well, all, hehe

2018-03-09 15:59 UTC, tarteo commented
@pedrobaeza You want me to squash every commit into 1 :S?

2018-03-09 16:00 UTC, pedrobaeza commented
hahaha, no, of course, but I mean both old and new commits by logical set/author. Now it's perfect :wink:

2018-03-09 16:02 UTC, tarteo commented
@pedrobaeza Ok, hahaha :smile:

2018-03-09 16:36 UTC, merged