[9.0] Keychain account caching
OCA/server-tools pull request #1168
Opened 2018-02-22 09:23 UTC by andreparames

This commit creates a computed field on the keychain backend, so that repeated calls to `_get_keychain_account()` will return the value from the ORM cache rather than repeating the query each time.

This PR depends on the [backport of features from 10.0](https://github.com/OCA/server-tools/pull/1165).

2018-02-22 09:34 UTC, lmignon requested changes

2018-02-22 09:34 UTC, lmignon commented on keychain/models/keychain_backend.py
>              account = self.env['keychain.account'].create(vals)
@andreparames you should assign the created account to `self.keychain_account_id`

2018-05-22 10:06 UTC, ThomasBinsfeld approved these changes

2018-05-22 10:11 UTC, lmignon approved these changes
LGTM: (Code review only)

2018-10-01 08:17 UTC, ThomasBinsfeld approved these changes
Code and functional :+1:

2018-10-01 08:25 UTC, merged