[ADD] remote_base
OCA/server-tools pull request #1291
Opened 2018-06-18 20:44 UTC by etobella

Remote Base
===========

This module allows to store all the connected remotes (external ip addresses) to odoo.
It should be used with other modules in order to check remote's configurations.

Usage
=====

When installed, all remotes will be stored by `hostname` on `res.remote`.
They can be viewed on `Settings / Users & Companies / Remotes`.
The last Ip of the remote will be stored.

It could be interesting to integrate this module with [report-print-send,](https://github.com/OCA/report-print-send) because we could configure the printers by remote, not by user.

2018-06-19 11:17 UTC, JordiBForgeFlow approved these changes
:+1: Very nice!!

2018-06-19 16:19 UTC, aheficent commented on remote_base/models/res_users.py
> +    # HACK https://github.com/odoo/odoo/issues/24183
Odoo will not fix that so I guess the hack will remain.

2018-06-19 16:20 UTC, AaronHForgeFlow approved these changes
:+1: functional test + human readable code review :smile:

2018-06-20 10:08 UTC, tarteo requested changes

2018-06-20 10:08 UTC, tarteo commented on remote_base/models/res_users.py
> +            remote.ensure_one()
Is this necessary? The variable is not used anywhere. 
I don't really understand the intention of this file. Why do you need to override the normal login method? Can you please explain? Thank you :+1:

2018-06-20 10:26 UTC, etobella commented on remote_base/models/res_users.py
> +            remote.ensure_one()
This way, the remote is generated on login (even on failures). These way, we can configure them.
Moreover, remote may not be used in this modules, but it is interesting on printing. remote-print-send is configured by user, but some companies need it by computer (remote).

2018-06-20 10:38 UTC, tarteo commented on remote_base/models/res_users.py
> +            remote.ensure_one()
Alright I understand now, thanks!

2018-06-20 10:38 UTC, tarteo approved these changes

2018-06-20 10:50 UTC, merged

2018-06-20 10:54 UTC, pedrobaeza commented
Please rename this to `base_remote` now this is just merged, as the nomenclature is not correct.

2018-06-20 11:01 UTC, etobella commented
It should be `remote_base`?