[10.0][MIG] base_import_odoo
OCA/server-tools pull request #1319
Opened 2018-07-19 07:24 UTC by hbrunn

relevant commit is https://github.com/OCA/server-tools/pull/1319/commits/975a4e40d60d24142698c69b798283e6c9ab90f7 and I took #1294 with me too

2018-08-17 04:22 UTC, hieulucky111 commented on base_import_odoo/models/__init__.py
> +from . import ir_model_data
import order

2018-08-17 04:24 UTC, hieulucky111 commented on base_import_odoo/models/import_odoo_database.py
> +from openerp import _, api, exceptions, fields, models, tools
i think we should use odoo instead openerp.

2018-11-30 15:02 UTC, sebalix requested changes
s/openerp/odoo/ in the import statements is welcome

2019-04-18 09:45 UTC, hbrunn commented
@hieulucky111 @sebalix thanks for the input, I fixed those back then, but didn't ping you. Could you re-review?

2019-04-18 10:26 UTC, sebalix approved these changes
Minor comment, LG!

2019-04-18 10:26 UTC, sebalix commented on base_import_odoo/__manifest__.py
> +    "version": "10.0.1.0.1",
No need to reset to `10.0.1.0.0`?

2019-04-18 12:56 UTC, hbrunn commented on base_import_odoo/__manifest__.py
> +    "version": "10.0.1.0.1",
thanks, did that

2019-04-22 22:41 UTC, tbaden requested changes
code review

2019-04-22 22:41 UTC, tbaden commented on base_import_odoo/__manifest__.py
> +    "summary": "Import records from another Odoo instance",
please add website tag with value https://github.com/OCA/server-tools

2019-04-23 06:51 UTC, hbrunn commented on base_import_odoo/__manifest__.py
> +    "summary": "Import records from another Odoo instance",
thanks, done

2019-04-23 06:53 UTC, tbaden approved these changes

2019-05-02 07:56 UTC, rousseldenis commented
@OCA/core-maintainers

2019-07-08 16:21 UTC, hbrunn commented
/ocabot merge

2019-07-08 17:38 UTC, closed without merging