[FIX] dbfilter_from_header: prevent autoloading
OCA/server-tools pull request #1326
Opened 2018-07-26 16:52 UTC by nilshamerlinck

2018-07-26 21:06 UTC, sbidoul approved these changes

2018-07-29 16:33 UTC, RoelAdriaans requested changes
No change of the description to mention that proxy_mode should be true?

2018-07-29 17:06 UTC, nilshamerlinck commented
@RoelAdriaans I've just changed the description to take into account your suggestion. Thanks!

2018-07-29 17:11 UTC, RoelAdriaans approved these changes

2018-08-08 07:22 UTC, merged