[11.0] mig menu_technical_info
OCA/server-tools pull request #1332
Opened 2018-07-30 10:19 UTC by jlzhou

2018-08-17 04:15 UTC, hieulucky111 approved these changes

2018-08-17 05:53 UTC, pedrobaeza commented
Please check Travis

2018-09-13 16:48 UTC, novawish approved these changes
LGTM, however i think travis's fail is due to module `onchange_helper`

PS: I re-run and it passed

2018-09-14 15:43 UTC, tafaRU requested changes
Tested on runbot.
Just some nitpicking otherwise LGTM

Also please take the opportunity to regenerate README file by using `oca-gen-addon-readme` according to
https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst

See https://github.com/OCA/account-invoice-reporting/commit/a9e186184eae245c30025f499f2abc627760e74b#r29918747 for further info.

2018-09-14 15:43 UTC, tafaRU commented on menu_technical_info/__init__.py
> +# -*- coding: utf-8 -*-
remove coding utf-8 line, since it's already the standard for Python3 (everywhere)

2018-09-14 15:43 UTC, tafaRU commented on menu_technical_info/__init__.py
> +# © 2016 Onestein (<http://www.onestein.eu>)
replace `©` by `Copyright` according to https://github.com/OCA/maintainer-tools/blob/master/template/module/__manifest__.py#L2 (everywhere)

2018-09-14 15:43 UTC, tafaRU commented on menu_technical_info/__manifest__.py
> +    'website': 'http://www.onestein.eu, http://www.maxsns.com',
please, don't use company websites but https://github.com/OCA/maintainer-tools/blob/master/template/module/__manifest__.py#L10

2023-07-02 12:29 UTC, closed without merging