[10.0][ADD]  Exception type as warning
OCA/server-tools pull request #1360
Opened 2018-09-19 12:12 UTC by TDu

Allow to tag an exception as a warning. Contrary to a regular exception
a warning will not be raised but not be blocking.

2018-09-28 12:22 UTC, Tonow-c2c commented on base_exception/models/base_exception.py
> +        string='Warning only',
Translation already added ?

2019-03-20 22:03 UTC, grindtildeath reviewed
LGTM :+1: 
Can you please rebase and increase module's version number ?

2019-03-29 09:31 UTC, bealdav commented
ping @hparfr

2019-04-29 15:30 UTC, hparfr reviewed
Hi,

I don't see why you need this.
You can already check a subset of rules in your own module with `_rule_domain`.
Blocking or not if there is some exceptions can be done in your own `test_exceptions`.

2019-04-30 07:49 UTC, TDu commented
Hello @hparfr, indeed this maybe achievable with a cusom `test_exceptions` method. But it is much more user friendly to be able to flag/see which exception are only warnings or not.
There is also an additional text for the warning which is handy.
One of the use case for this (which is live on a production instance) is on sale order lines. Warning only would be displayed on the line as additional information to not forget but they are not blocking to confirm the sale order.

2019-04-30 08:13 UTC, bealdav commented
@TDu thanks for this contribution. On my side I think it's a feature that can be implemented in another module (base_exception <> extended_exception ;-) ). 
Then, you can explain more precisely the use case and how implement it in sale for example.
Thanks a lot

2019-07-09 09:35 UTC, grindtildeath approved these changes

2019-07-15 14:20 UTC, i-vyshnevska approved these changes

2019-07-15 15:04 UTC, hparfr requested changes
Please create another module in order to keep base_exception module away from the warning logic.
Most of the dependencies (purchase, sale, product?) of base_exception don't have to deal with warnings.

2019-08-06 16:04 UTC, yvaucher commented on base_exception/models/base_exception.py
> +             'For a sale order line it could be the product name sold.'
Missing a space before `For`

2023-08-06 12:24 UTC, closed without merging