[ADD] profiler: Integration of python cprofile and postgresql logging collector for Odoo
OCA/server-tools pull request #1369
Opened 2018-09-27 10:11 UTC by moylop260

2018-10-01 08:18 UTC, moylop260 commented
@carlosdauden 
This is the module that I talked with you

2018-10-01 10:11 UTC, etobella commented
Amazing!!! Will it be ported to 11.0?

I tested it, and it worked like a charm!

2018-10-01 12:10 UTC, mreficent commented
What is the difference between this profiler and the `odoo.tools.profiler`? Because if they are not the same, maybe they should not have the same name.

2018-10-03 14:16 UTC, yajo requested changes

2018-10-03 14:16 UTC, yajo commented on profiler/models/profiler_profile.py
> +    date_finished = fields.Char(readonly=True)
Why not `fields.Datetime()`?

2018-10-03 14:16 UTC, yajo commented on profiler/models/profiler_profile.py
> +                              default=_find_loggers_path)
Use a lambda please. This allows to override the method without overriding the field, and allows to sort default methods, putting them below fields.

2018-10-03 14:16 UTC, Yajo commented on profiler/models/profiler_profile.py
> +            self.description += "\nPgbadger output is empty!"
AFAIK each `self.description +=` will issue a `self.write()` from the ORM. Isn't it better to just use a normal variable and assign only once at the end?

2018-10-03 14:16 UTC, Yajo commented on profiler/models/profiler_profile.py
> +            pgbadger_bin = tools.find_in_path('pgbadger')
This is missing in the manifest.

2018-10-03 14:16 UTC, Yajo commented on profiler/models/profiler_profile.py
> +                     'variable PGOPTIONS? %s', pgoptions_enabled)
Does this make sense? :thinking: What if Postgres is in a different server?

To check enabled options, shouldn't you get those from the database itself?

2018-10-03 14:16 UTC, Yajo commented on profiler/models/profiler_profile.py
> +            "You need seudo-enable logs from your "
"pseudo"

2018-10-03 14:16 UTC, Yajo commented on profiler/models/profiler_profile.py
> +            "postgresql-server configuration file.\n"
Any chance for this very addon to enable those options? Using https://www.postgresql.org/docs/current/static/sql-set.html or similar?

2018-10-03 14:16 UTC, Yajo commented on profiler/models/profiler_profile.py
> +            # pylint: disable=sql-injection
You can use [`AsIs`](http://initd.org/psycopg/docs/extensions.html#psycopg2.extensions.AsIs) in the params tuple and avoid this line.

2018-10-03 14:16 UTC, Yajo commented on profiler/models/profiler_profile.py
> +            cr.execute('SHOW %s' % param)
Possible SQL injection? :thinking: :warning:

2018-10-03 14:16 UTC, Yajo commented on profiler/tests/__init__.py
> +# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
I wouldn't put these lines if they amount more than the code itself :grin:

2018-12-03 08:42 UTC, bealdav commented on profiler/hooks.py
> +from openerp.sql_db import Cursor
Oops openerp in v12 ?

2018-12-15 14:49 UTC, etobella commented
I backported the module to v11 using your original code, but I discovered that it is not checking the external xmlrpc calls. https://github.com/etobella/server-tools/tree/11.0-mig-profiler (I will propose the  PR to OCA once it is approved on v12).
On our case, odoo is integrated with another system through xmlrpc calls. However, profiler is not checking this calls. Do you know why?

2018-12-17 16:20 UTC, etobella commented
I found the problem, currently, the system is only patching the WebRequest. I have made some changes on my branch in order to review also xmlrpc calls. I also added a filter for the profile lines.
https://github.com/etobella/server-tools/commit/8b6ff7dbfd5b552403762f95c31d3a059ed8b893

2018-12-18 10:26 UTC, etobella commented
@moylop260 If you are reusing my commit, you should maintain me as the author...

2018-12-18 11:09 UTC, moylop260 commented
Hi @etobella 
I hope you are doing well!

Thanks for your contribution.

For next time, you can create a  PR to my dev-branch.
Regards!

If you have change to fix another feedback it is welcome, since that I didn't find time yet.
Thank you

2023-08-13 12:23 UTC, closed without merging