[11.0] [MIG] base_view_inheritance_extension: Migration to v11.0
OCA/server-tools pull request #1407
Opened 2018-10-26 11:56 UTC by sergio-teruel

cc @Tecnativa
WIP

2018-10-27 16:34 UTC, pedrobaeza reviewed
Please squash adjacent transbot commits + pre-generate README

2018-10-29 10:58 UTC, sergio-teruel commented
@pedrobaeza done!

2018-12-04 21:06 UTC, NL66278 commented on base_view_inheritance_extension/__init__.py
> +# © 2016 Therp BV <http://therp.nl>
Copyright can/should be removed from __init__.py files.

2018-12-04 21:07 UTC, NL66278 commented on base_view_inheritance_extension/__manifest__.py
> +# © 2016 Therp BV <http://therp.nl>
Both copyright for Therp BV and licence stuff can/should be changed to https. Copyright symbol should be replaced by the word Copyright.

2018-12-04 21:12 UTC, NL66278 requested changes
Some minor style improvements needed before approval. See other comments.

2019-01-11 11:58 UTC, cubells approved these changes
If you do changes requested :+1: 

LGTM

2019-01-17 08:43 UTC, NL66278 commented
@sergio-teruel Are you going to take up the review comments?

2019-01-17 08:52 UTC, pedrobaeza commented
@NL66278 I have just made the requested changes.

2019-01-17 13:33 UTC, NL66278 approved these changes
:+1:  Comments done and LGTM

2019-01-17 13:37 UTC, merged