[ADD] 10.0 base_group_permission_information module
OCA/server-tools pull request #1462
Opened 2018-12-18 10:17 UTC by damdam-s

2018-12-18 10:29 UTC, nbessi approved these changes

2019-01-18 07:45 UTC, simahawk requested changes
also, remove empty files from `readme` folder

2019-01-18 07:45 UTC, simahawk commented on base_group_permission_information/models/access.py
> +    create_int = fields.Integer(compute=compute_perm_int_vals, store=True)
do we really need these for pivot only?
If mandatory, then add a comment pls

2019-01-18 07:45 UTC, simahawk commented on base_group_permission_information/models/access.py
> +    create_int = fields.Integer(compute=compute_perm_int_vals, store=True)
same

2019-01-18 07:45 UTC, simahawk commented on base_group_permission_information/readme/DESCRIPTION.rst
> +Displays:
a screenshot would be nice

2023-11-05 12:25 UTC, closed without merging