[10.0] base user role multicompany adapation
OCA/server-tools pull request #1489
Opened 2019-01-29 15:07 UTC by PierrickBrun

With this PR, a user role is now company dependent, that means you don't have the same roles depending on the active company.

A user can then switch company and have different roles applied.

2019-01-29 15:36 UTC, sebastienbeau requested changes
Hi Pierrick can you
- add a python constraint that check that the company on the role line is one of the company available on the customer?
- add python unit test

2019-01-29 15:36 UTC, sebastienbeau commented on base_user_role/models/user.py
>              for role_line in role_lines:
You can just set this code on the same line for "role_line in user._get_enabled_roles()"

2019-01-29 15:36 UTC, sebastienbeau commented on base_user_role/models/user.py
> +            rec.company_id == rec.user_id.company_id)
In case that the role is not restricted to one specific company we should apply it to all company

2019-01-31 15:21 UTC, PierrickBrun commented
@sebastienbeau all requested changes are addressed

2019-02-04 15:20 UTC, bealdav commented
ping @sebalix, could you have a look to this PR ?
I think it adds a really good value to the module.

2019-02-04 16:00 UTC, sebastienbeau commented on base_user_role/models/role.py
> +    @api.one
@api.one is deprecated

2019-02-04 16:00 UTC, sebastienbeau commented on base_user_role/models/role.py
> +        if self.company_id and self.company_id != self.user_id.company_id and(
no need to make this double check, user.company_ids include user.company_id

2019-02-04 16:00 UTC, sebastienbeau commented on base_user_role/models/role.py
> +                'User "{}" does not have access to the company "{}"'.format(
Translation "_(" is missing

2019-02-04 16:37 UTC, sebalix approved these changes
LGTM, nice addition!

2019-02-05 15:57 UTC, PierrickBrun commented on base_user_role/models/role.py
> +        if self.company_id and self.company_id != self.user_id.company_id and(
In a non-multicompany context, company_ids can be empty but company_id isn't

2019-02-06 09:35 UTC, bealdav commented
Please @benwillig could you have a look please ?

2019-02-08 10:13 UTC, benwillig reviewed
Nice feature @PierrickBrun.
Code LGTM.

But don't we need record rules for ```res.users.role.line``` as it is company dependent now ?

2019-02-08 13:39 UTC, sebastienbeau commented on base_user_role/models/role.py
> +        if self.company_id and self.company_id != self.user_id.company_id and(
you right

2019-02-08 13:49 UTC, sebastienbeau requested changes

2019-02-08 13:49 UTC, sebastienbeau commented on base_user_role/models/role.py
> +            if (self.company_id and
replace "self" by "record" as you are in the loop. Current code will not work 

Maybe the code can be simplify (more explicit) with
allowed_companies = record.user_id.company_id + record.user_id.company_ids
if record.company_id and record.company_id not in allowed_companies:
   raise ...

2019-03-06 11:40 UTC, PierrickBrun commented
@sebastienbeau can you look at it again ?

2019-03-07 01:04 UTC, elicoidal approved these changes
LGTM
Excellent feature addition

2019-03-08 12:14 UTC, sebastienbeau approved these changes

2019-03-08 12:15 UTC, merged