[FIX] Use _compute_session_token to invalidate user sessions on auth_session_timeout
OCA/server-tools pull request #1495
Opened 2019-01-31 14:45 UTC by daramousk

2019-02-14 13:11 UTC, daramousk commented
@NL66278 A review on this would be awesome, according to @lfreeke this has already been deployed and working

2019-02-18 08:33 UTC, NL66278 approved these changes
:+1: Tested by coworker and looks good to me.

2019-03-13 10:43 UTC, daramousk commented
@hbrunn Going to need an extra review for this one to be merged.

2019-03-13 11:27 UTC, hbrunn requested changes
please adapt tests so that your code is actually hit by them

2019-03-22 13:41 UTC, daramousk commented
@hbrunn Done, also took the liberty of adding some docstrings on the functions.

2019-03-25 12:42 UTC, hbrunn approved these changes

2019-03-25 13:01 UTC, merged

2019-04-02 13:09 UTC, anassahmed commented
The method `_compute_session_token` isn't called with each request like `check` was.

In `11.0` version of `auth_session_timeout`; it uses `_authenticate` in `ir.http` model, which is called with each request (we've been using the `11.0` version with our Odoo `10.0` instance for some time now).