12.0 mig base view inheritance extension
OCA/server-tools pull request #1529
Opened 2019-03-14 18:47 UTC by rvalyi

standard migration: nothing to be done: same code as version 11 (except version number)

cc @hbrunn @NL66278 @pedrobaeza @sergio-teruel @alexis-via

2019-03-14 20:01 UTC, alexis-via commented
It seems you forgot the update of the version number.

2019-03-14 20:11 UTC, rvalyi commented
@alexis-via sorry. I now amended the commit with the right version

2019-03-14 21:12 UTC, rvalyi commented
@alexis-via sorry, I did it wrong as I was in a meeting with Renato. I should not have changed the version in the Transiflex pot commit, so I undo that and I added a new commit for it https://github.com/OCA/server-tools/pull/1529/commits/61a83bb372dc83d6344993034ad0ee6123846d53
Should be good now, sorry again.

2019-03-15 04:00 UTC, hbrunn commented
v12 has its own version of `position="move"`, cf https://github.com/OCA/OCB/blob/12.0/odoo/addons/base/models/ir_ui_view.py#L650 ff and https://www.odoo.com/documentation/12.0/reference/views.html#inheritance-specs (note at the end).

It seems to me both can coexist, and I find the way they have chosen a little bit clumsy, but it serves the same purpose. Should we drop support for `position="move"` here for consistency or keep it for simpler migrations of modules using it and a imho nicer syntax?

2019-03-15 07:17 UTC, NL66278 commented
@hbrunn I would people encourage to use the standard Odoo way as much as possible. So keep the position="move" for now, but clearly mark/document it as deprecated.

2019-03-15 08:38 UTC, pedrobaeza commented
But are they going to conflict having the same name?

2019-03-15 08:46 UTC, hbrunn commented
no, because for Odoo standard, the attribute is supposed to be added to a child of the element you match, in our version it's on the element you match

2019-03-15 08:51 UTC, pedrobaeza commented
Pretty confusing, isn't it? I prefer to remove it...

2019-03-29 08:49 UTC, bealdav commented
Any decision here ?

2019-04-21 17:14 UTC, tbaden commented
I would prefer to use odoo core behaviour, but just my opinion. nothing against this feature, but to have both will be quite confusing.

2019-05-28 12:50 UTC, astirpe commented
I would prefer the position="move" removed from this module. Just a preference, not blocking for this.

2019-09-04 14:22 UTC, ernestotejeda commented
@rvalyi, what conclusion do we get here? What can we do to conclude with this migration?
maybe drop support for position="move" here is good idea, what do you think? ;-)

2019-09-04 14:40 UTC, hbrunn commented
note that since version 9, also the `list_{add,remove}` parts can be done with Odoo core: https://github.com/OCA/OCB/commit/f962b0f62831614137a9e1e509803bfa39be1110 (actually in a nicer way because you can also select a separator) - so if we deprecate the moving, we also should deprecate that

2019-09-04 15:00 UTC, ernestotejeda commented
> note that since version 9, also the `list_{add,remove}` parts can be done with Odoo core: [OCA/OCB@f962b0f](https://github.com/OCA/OCB/commit/f962b0f62831614137a9e1e509803bfa39be1110) (actually in a nicer way because you can also select a separator) - so if we deprecate the moving, we also should deprecate that

Yes, i agree with you @hbrunn  :ok_hand:

2019-12-01 19:14 UTC, tsabi commented
Hi, when will you merge this? A lot of module depends from this.
Thanks, Csaba

2019-12-02 08:21 UTC, NL66278 commented on base_view_inheritance_extension/__init__.py
> +# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl.html).
Make license lines https:

2019-12-02 08:31 UTC, NL66278 requested changes
I agree that all the methods that are now in standard Odoo should be removed. Either completely, or at least by giving a Deprecated message when still used (to be turned into an Exception in 13.0).

2019-12-02 21:53 UTC, rvalyi commented
Hello folks, I dont really use this module myself. So if somebody wants to redo the migration in another PR/another way please feel free to go ahead as I cannot dedicate time to this one these days unfortunately...

2020-03-02 12:07 UTC, alexis-via commented
I continued the work of @rvalyi and removed the features which are now native. The readme of the module has been updated. Tests works fine. I also tested it with my PR https://github.com/OCA/account-invoicing/pull/570 which makes use of this module in v12 and it works well. So it's ready to merge now.

2020-03-02 12:57 UTC, bealdav approved these changes
LGTM

2020-03-02 13:23 UTC, alexis-via commented on base_view_inheritance_extension/__init__.py
> +# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl.html).
done

2020-03-03 14:24 UTC, alexis-via commented
As said by Pedro in the PR for v13, the list_add and list_remove feature is NOT native. So I cancelled my previous commit and push a new commit with only the removal of the move feature.
I took into account all the remarks of the reviewers. So it's now ready to merge.

2020-03-03 15:09 UTC, pedrobaeza approved these changes

2020-03-03 15:10 UTC, pedrobaeza commented
/ocabot merge

2020-03-03 15:36 UTC, merged