[ADD] webhook: Add standard webhook odoo module. [ADD] webhook_github: Add webhook github odoo module.
OCA/server-tools pull request #193
Opened 2015-06-26 00:59 UTC by moylop260

2015-07-22 07:17 UTC, dreispt commented on webhook/README.md
> +Module to receive [global webhooks](https://es.wikipedia.org/wiki/Webhook) events.
Use link to english Wikipedia?

2015-07-22 07:19 UTC, dreispt commented on webhook/README.md
> +`def run_CONSUMER_EVENT*`
Why the star?
Maybe say: "The webhook events will be processed by your custom methods, that should be prefixed with `run_`"

2015-07-22 07:21 UTC, dreispt commented on webhook/controllers/main.py
> +import pprint
remove

2015-07-22 07:21 UTC, dreispt commented on webhook/controllers/main.py
> +#    All Rights Reserved.
No license info

2015-07-22 07:25 UTC, dreispt commented on webhook/controllers/main.py
> +        NOTE: Important use --db-filter params in odoo start.
It's important to mention this in the README

2015-07-22 07:29 UTC, dreispt commented on webhook/__init__.py
> +# -*- encoding: utf-8 -*-
s/encoding/coding
True for all code files

2015-07-22 07:36 UTC, dreispt commented on webhook/views/webhook_views.xml
> +        <menuitem id="main_webhook_menu" name="Webhook"/>
No parent menu? IMO is should be under Settings / Technical / Automation..

2015-07-22 07:38 UTC, dreispt commented
Did some style related comments, but I honestly don't have the technical skill to discuss the semantics of the code.

2015-07-23 11:58 UTC, moylop260 commented
@dreispt 
Thank for you comment's
I will to work ASAP

2015-07-30 16:28 UTC, pedrobaeza commented
This is pending on the creation of the new repo

2015-08-04 13:04 UTC, dreispt commented
@pedrobaeza What repo?

2015-08-04 13:20 UTC, pedrobaeza commented
webhook repo. It was discussed and it was seen convenient to create it. It's pending from one of our side (board). I will take care of it in the coming days.

2016-06-02 22:51 UTC, alan196 commented
I just tested this module with odoo 8.0 and 9.0 works fine :+1: 
I made a module with this and it works with no issues.

2016-09-22 12:55 UTC, bealdav commented
nice feature, thanks

2016-09-22 17:58 UTC, moylop260 commented
@bealdav 
You're welcome.

@pedrobaeza @dreispt @gurneyalex 
With the new structure of server-tools: Are there a place for the module of webhooks?

2016-09-22 18:33 UTC, pedrobaeza commented
We should move first to create all the repositories, and I think we can include it in any of them for sure.

2016-09-22 18:33 UTC, pedrobaeza commented
Should we wait until the code sprint?

2016-09-22 18:38 UTC, moylop260 commented
Ok, We will discuss on oca sprint
Thanks for reply

2017-05-20 14:02 UTC, gurneyalex commented
@moylop260 what is the status of this PR?

2017-05-22 15:28 UTC, moylop260 commented
This PR add a webhook standard module
In the past, I think that we should be this module with a project separated but I'm considering that is not necessary.
So we could integrate it to server-tools

2017-08-30 15:45 UTC, sebalix requested changes

2017-08-30 15:45 UTC, sebalix commented on webhook/data/webhook_data.xml
> +        </record>
This GitHub configuration should be part of the demo data, or at least with a ``noupdate="1"``?
We are testing this module, this piece of code is OK excepted the IP address (`192.30.253.0/22` here).

2018-05-04 00:39 UTC, pedrobaeza commented
@moylop260 are you still interested in this? Should we merge?

2018-05-04 15:24 UTC, moylop260 commented
Superseded by https://github.com/OCA/server-tools/pull/957
Let's wait a backport work from another contributor...

2018-05-04 15:24 UTC, closed without merging