[14.0][mig]html_image_url_extractor
OCA/server-tools pull request #2127
Opened 2021-07-02 05:31 UTC by hkapatel-initos

2021-07-02 12:07 UTC, fshah-initos approved these changes
LGTM.  No major change

2021-07-06 05:25 UTC, hkapatel-initos commented
@Víctor Martínez it would be nice if could you review it here.

2021-07-06 09:14 UTC, victoralmau requested changes
Good job, only some little changes related to purge translations.

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/am.po
> +#~ msgstr "Última actualización en"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/ar.po
> +#~ msgstr "آخر تحديث في"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/bg.po
> +#~ msgstr "Последно обновено на"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/bs.po
> +#~ msgstr "Zadnje ažurirano"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/cs.po
> +#~ msgstr "Naposled upraveno"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/da.po
> +#~ msgstr "Sidst opdateret den"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/el_GR.po
> +#~ msgstr "Τελευταία ενημέρωση στις"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/en_GB.po
> +#~ msgstr "Last Updated on"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/es_AR.po
> +#~ msgstr "Última actualización el"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/es_CL.po
> +#~ msgstr "Última actualización en"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/es_CO.po
> +#~ msgstr "Actualizado"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/es_CR.po
> +#~ msgstr "Ultima actualización en"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/es_DO.po
> +#~ msgstr "Última actualización en"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/es_EC.po
> +#~ msgstr "Última actualización en"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/es_MX.po
> +#~ msgstr "Ultima actualización realizada"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/es_PE.po
> +#~ msgstr "Ultima Actualización"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/es_PY.po
> +#~ msgstr "Ultima actualización en"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/es_VE.po
> +#~ msgstr "Ultima actualizacion en"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/et.po
> +#~ msgstr "Viimati uuendatud"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/eu.po
> +#~ msgstr "Last Updated on"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/fa.po
> +#~ msgstr "آخرین به روز رسانی در"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/fi.po
> +#~ msgstr "Viimeksi päivitetty"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/fr.po
> +#~ msgstr "Dernière mise à jour le"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/fr_CA.po
> +#~ msgstr "Dernière mise à jour le"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/fr_CH.po
> +#~ msgstr "Modifié le"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/gl.po
> +#~ msgstr "Última actualización en"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/he.po
> +#~ msgstr "עודכן לאחרונה על"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/hr.po
> +#~ msgstr "Zadnje ažuriranje"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/hr_HR.po
> +#~ msgstr "Zadnje ažurirano"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/hu.po
> +#~ msgstr "Utoljára frissítve "
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/id.po
> +#~ msgstr "Diperbaharui pada"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/ja.po
> +#~ msgstr "最終更新日"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/ko.po
> +#~ msgstr "최근 갱신 날짜"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/lt.po
> +#~ msgstr "Paskutinį kartą atnaujinta"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/lt_LT.po
> +#~ msgstr "Paskutinį kartą atnaujinta"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/lv.po
> +#~ msgstr "Pēdējās izmaiņas"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/mk.po
> +#~ msgstr "Последно ажурирање на"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/mn.po
> +#~ msgstr "Сүүлийн засвар хийсэн огноо"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/nb.po
> +#~ msgstr "Sist oppdatert"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/nb_NO.po
> +#~ msgstr "Sist oppdatert den"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/nl.po
> +#~ msgstr "Laatst bijgewerkt op"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/nl_BE.po
> +#~ msgstr "Laatst bijgewerkt op"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/pl.po
> +#~ msgstr "Ostatnia zmiana"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/pt.po
> +#~ msgstr "Atualizado pela última vez em"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/pt_BR.po
> +#~ msgstr "Última atualização em"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/pt_PT.po
> +#~ msgstr "Atualizado pela última vez em"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/ro.po
> +#~ msgstr "Ultima actualizare la"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/ru.po
> +#~ msgstr "Последний раз обновлено"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/sk.po
> +#~ msgstr "Naposledy upravené"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/sl.po
> +#~ msgstr "Zadnjič posodobljeno"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/sr.po
> +#~ msgstr "Kreiran"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/sr@latin.po
> +#~ msgstr "Zadnja izmjena"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/sv.po
> +#~ msgstr "Senast uppdaterad"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/th.po
> +#~ msgstr "อัพเดทครั้งสุดท้ายเมื่อ"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/tr_TR.po
> +#~ msgstr "En son güncelleme tarihi"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/uk.po
> +#~ msgstr "Останнє оновлення"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/vi.po
> +#~ msgstr "Cập nhật lần cuối vào"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/vi_VN.po
> +#~ msgstr "Cập nhật lần cuối vào"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/zh_CN.po
> +#~ msgstr "上次更新日期"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/i18n/zh_TW.po
> +#~ msgstr "最後更新於"
```suggestion
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/readme/DESCRIPTION.rst
> +<https://github.com/OCA/website/tree/9.0/website_blog_excerpt_img>`_: blog list shows the first
```suggestion
<https://github.com/OCA/website/tree/14.0/website_blog_excerpt_img>`_: blog list shows the first
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/static/description/index.html
> +<p>It is useful for modules such as <a class="reference external" href="https://github.com/OCA/website/tree/9.0/website_blog_excerpt_img">website_blog_excerpt_img</a>: blog list shows the first
```suggestion
<p>It is useful for modules such as <a class="reference external" href="https://github.com/OCA/website/tree/14.0/website_blog_excerpt_img">website_blog_excerpt_img</a>: blog list shows the first
```

2021-07-06 09:14 UTC, victoralmau commented on html_image_url_extractor/tests/test_extractor.py
> +        super(ExtractorCase, self).setUp()
```suggestion
        super().setUp()
```

2021-07-06 12:21 UTC, hkapatel-initos commented
> Good job, only some little changes related to purge translations.

Thanks for your suggestion some changes are done, as per my experience we don't update the translation.

2021-07-06 13:01 UTC, victoralmau commented
> > Good job, only some little changes related to purge translations.
> 
> Thanks for your suggestion some changes are done, as per my experience we don't update the translation.

Ok, thanks, although translations purge not appear in migration guideline is a better work because transbot not do it.

2021-07-06 13:01 UTC, victoralmau approved these changes

2021-07-08 03:58 UTC, hkapatel-initos commented
@pedrobaeza  It would be great if you could try to merge it.

2021-07-08 06:08 UTC, pedrobaeza commented
/ocabot merge nobump

2021-07-08 06:27 UTC, merged