[15.0][mig] database cleanup
OCA/server-tools pull request #2219
Opened 2021-12-03 11:32 UTC by damdam-s

based on #1990

2022-03-28 07:14 UTC, gurneyalex commented
https://github.com/damdam-s/server-tools/pull/1 fixes an issue I had with this version.

2022-05-12 13:39 UTC, JuanyDForgeflow commented
@damdam-s  Can you check the tests?

2022-06-14 07:38 UTC, gurneyalex commented
/ocabot merge nobump

2022-08-29 11:06 UTC, leemannd commented
Original 14.0 PR has been superseed by -> database_cleanup https://github.com/OCA/server-tools/pull/2390

2022-09-26 04:30 UTC, AungKoKoLin1997 requested changes

2022-09-26 04:30 UTC, AungKoKoLin1997 commented on database_cleanup/views/purge_menus.xml
> +            action = env.get('cleanup.purge.wizard').get_wizard_action()
```suggestion
            action = env.get('cleanup.purge.wizard.menu').get_wizard_action()
```

2022-09-26 04:30 UTC, AungKoKoLin1997 commented on database_cleanup/views/purge_menus.xml
> +            action = env.get('cleanup.purge.wizard').get_wizard_action()
I tested in local environment and get error "You are not allowed to create 'Purge stuff' (cleanup.purge.wizard) records." when click "Purge absolete menu entries". I think you should use the model of current menu.

2022-09-27 10:04 UTC, leemannd commented
Hello @damdam-s the 14.0 has been merged from another PR that superseeds the one you have been using. Do you have time to take a look at it?

2023-02-09 11:25 UTC, pedrobaeza commented
Superseded by #2547

2023-02-09 11:25 UTC, closed without merging