15.0 mig base exception fix
OCA/server-tools pull request #2319
Opened 2022-03-23 09:50 UTC by damdam-s

tentative to fix #2279

2022-03-23 14:08 UTC, damdam-s commented
superseeds #2279 

splits base_exception module in 2 modules: 

- base_exception for the behaviour
- test_base_exception for the tests

I did that because model loading "on the fly" does not work

2022-03-30 14:16 UTC, nicomacr approved these changes
LGTM

2022-05-03 13:11 UTC, ivantodorovich approved these changes

2022-05-31 17:57 UTC, mylbco commented
When will this be merged ?

2022-06-24 07:22 UTC, leemannd approved these changes

2022-07-06 11:50 UTC, cesar-tecnativa requested changes

2022-07-06 11:50 UTC, cesar-tecnativa commented on test_base_exception/tests/test_base_exception.py
> -
do not remove tests

2022-07-06 11:50 UTC, cesar-tecnativa commented on test_base_exception/tests/test_base_exception.py
> -            ("base.exception.test.purchase.line", "Purchase Order Line")
do not remove tests

2022-07-12 05:00 UTC, cesar-tecnativa commented on test_base_exception/tests/test_base_exception.py
> -            ("base.exception.test.purchase.line", "Purchase Order Line")
I did a new PR https://github.com/OCA/server-tools/pull/2366 that solves this problem

2022-07-12 14:10 UTC, pedrobaeza commented
Superseded by #2366

2022-07-12 14:10 UTC, closed without merging