16.0 mig database cleanup
OCA/server-tools pull request #2473
Opened 2022-11-24 14:32 UTC by JoelZilli

2023-01-04 13:35 UTC, sebalix commented
/ocabot migration database_cleanup

2023-02-02 11:32 UTC, gurneyalex approved these changes

2023-02-24 07:52 UTC, gbrito-erpopen approved these changes

2023-03-02 12:35 UTC, santostelmo approved these changes

2023-03-02 21:33 UTC, pedrobaeza commented
/ocabot merge nobump

2023-03-04 18:32 UTC, pedrobaeza commented
Can you please rebase and check the tests, that seems to be failing?

2023-03-23 12:13 UTC, StephaneMangin approved these changes

2023-03-23 12:14 UTC, StephaneMangin commented
cc @pedrobaeza Feel free to approve if it's ok you.

2023-03-23 12:38 UTC, pedrobaeza commented
/ocabot merge nobump

2023-03-23 12:43 UTC, pedrobaeza commented
There's still problems in tests, and in fact, this PR doesn't contain right now any CI check. Don't know why. Please rebase again.

2023-03-23 12:49 UTC, gurneyalex commented
/ocabot merge nobump

2023-03-23 14:05 UTC, StephaneMangin commented
@JoelZilli Please integrate this commit to fix the CI issue.

https://github.com/yankinmax/server-tools/pull/1/files

2023-03-23 14:16 UTC, gurneyalex commented
@JoelZilli I can't make a PR on your branch please cherry pick this commit https://github.com/gurneyalex/server-tools/commit/0bda5bc777c40ff38f4a0be1ac8f0ba7dfad4c4a

2023-03-28 12:01 UTC, paulius-sladkevicius commented
Got a few warning logs while testing it.

```
2023-03-28 11:45:22,085 1 WARNING odoodb odoo.api.create: The model odoo.addons.database_cleanup.models.purge_wizard is not overriding the create method in batch 
2023-03-28 11:45:22,085 1 WARNING odoodb odoo.api.create: The model odoo.addons.database_cleanup.models.purge_wizard is not overriding the create method in batch 
```

2023-04-08 02:47 UTC, hbrunn requested changes

2023-04-08 02:47 UTC, hbrunn commented on database_cleanup/models/purge_models.py
> +        return super()._drop_table()
this won't work, you really need to call super only on the restricted set

2023-04-08 02:47 UTC, hbrunn commented on database_cleanup/models/purge_models.py
> +        return super()._inherited_models()
see above

2023-04-08 02:47 UTC, hbrunn commented on database_cleanup/models/purge_models.py
> +        return super()._prepare_update()
see above

2023-04-08 04:08 UTC, hbrunn commented
please cherry pick https://github.com/hbrunn/server-tools/commit/e85698cecaa8ae15b2eabc8ed437e046bac165be for fixed module purging

2023-05-03 19:14 UTC, JoelZilli commented
On the migration of the module to 14 this "purge" (here https://github.com/OCA/server-tools/commit/b18e74e2dda7c02285e772cad1ddef080d9e111e#diff-1bd698f0fb309ad37089dfe60270acca4e447b5afa31a28aab9c358d7b9a4b72L80) call was removed and then all this lines are not making anything on the database. Instead of re-adding purge and removing modules automatically when entering the menu, we believe it's better to show uninstalled modules that are not available so that they can be removed togheter with the other modules.

2023-05-03 19:52 UTC, hbrunn commented
that was part of the commit I asked you to cherry pick above

2023-05-04 12:54 UTC, JoelZilli commented
Sorry, didn`t see that. I added your changes directly on my commit. Thanks!

2023-05-17 10:03 UTC, gurneyalex commented
Hello @JoelZilli  Can you cherry pick https://github.com/OCA/server-tools/commit/e8d68eb8db12d9aeb9e3ff9e6ba9d7dcdedbf301 (adapting the branch name in test.yml) to fix the CI?

2023-06-11 04:01 UTC, fmdl requested changes

2023-06-11 04:01 UTC, fmdl commented on database_cleanup/models/create_indexes.py
> +            self.env.cr.execute(
trigram index are not found

2023-06-11 04:01 UTC, fmdl commented on database_cleanup/security/ir.model.access.csv
> +access_cleanup_create_indexes_line,access_cleanup_create_indexes_line,model_cleanup_create_indexes_line,base.group_user,1,1,1,1
use this group : base.group_erp_manager, no ?

2023-06-11 04:01 UTC, fmdl commented on database_cleanup/views/purge_wizard.xml
> +                <div attrs="{'invisible': [('purge_line_ids', '!=', [])]}">
don't forget to add sheet.

2023-06-11 04:01 UTC, fmdl commented on database_cleanup/views/create_indexes.xml
> +                <attribute name="icon">gtk-add</attribute>
this icon doesn't exist

2023-06-11 04:01 UTC, fmdl commented on database_cleanup/models/purge_tables.py
> +            self.env.cr.execute("DROP TABLE %s", (IdentifierAdapter(line.name),))
maybe add cascade in `DROP TABLE %s CASCADE`, tu prevent any postgres error.

2023-07-17 11:39 UTC, StephaneMangin commented
@JoelZilli Could you cherry pick https://github.com/OCA/server-tools/commit/e8d68eb8db12d9aeb9e3ff9e6ba9d7dcdedbf301 please ? To fix the tests

2023-12-04 15:09 UTC, legalsylvain commented
Hi. What is the state of this PR ? Thanks !

2023-12-29 09:10 UTC, pedrobaeza commented
Superseded by #2684

2023-12-29 09:10 UTC, closed without merging