[15.0][MIG] scheduler_error_mailer: Migration to version 15.0
OCA/server-tools pull request #2553
Opened 2023-02-13 18:57 UTC by ernesto-garcia-tecnativa

@tecnativa TT41023

2023-02-13 19:08 UTC, ernesto-garcia-tecnativa commented
@pedrobaeza  @victoralmau  please review

2023-02-13 19:17 UTC, pedrobaeza commented
/ocabot migration scheduler_error_mailer

2023-02-14 08:04 UTC, victoralmau requested changes
Good work, just a few minor changes.

2023-02-14 08:04 UTC, victoralmau commented on scheduler_error_mailer/data/ir_cron_email_tpl.xml
> +<odoo noupdate="0">
```suggestion
<odoo noupdate="1">
```
Keep the same behaviour as before.

2023-02-14 08:04 UTC, victoralmau commented on scheduler_error_mailer/models/ir_cron.py
> +        comodel_name="mail.template",
```suggestion
        comodel_name="mail.template",
        domain=[("model_id.model", "=", "ir.cron")],
```
We can use the opportunity to add a domain.

2023-02-14 13:24 UTC, ernesto-garcia-tecnativa commented
> Good work, just a few minor changes.

Thank you, I push a new commit with your suggestions

2023-02-14 13:34 UTC, victoralmau commented
> > Good work, just a few minor changes.
> 
> Thank you, I push a new commit with your suggestions

Not necessary, all changes must be in the migration commit.

2023-02-14 13:52 UTC, ernesto-garcia-tecnativa commented
> > > Good work, just a few minor changes.
> > 
> > 
> > Thank you, I push a new commit with your suggestions
> 
> Not necessary, all changes must be in the migration commit.

Ready, I wait the tests

2023-02-14 14:00 UTC, victoralmau approved these changes
Code review OK.

2023-02-14 20:26 UTC, pedrobaeza approved these changes
/ocabot merge nobump

2023-02-14 20:55 UTC, merged