[MIG] attachment_unindex_content: Migration to 16.0
OCA/server-tools pull request #2563
Opened 2023-02-24 00:38 UTC by Rodrigosu-Vauxoo

- Manifest's "Version" updated to "16.0.1.0.0"
- Translation files updated to new version

2023-02-24 23:03 UTC, Rodrigosu-Vauxoo commented
Hello @luisg123v, could you please review this MR please?

2023-02-25 00:29 UTC, luisg123v requested changes

2023-02-25 00:29 UTC, luisg123v commented on .pre-commit-config.yaml
> +    rev: 5.12.0
Please avoid this change

2023-02-25 00:29 UTC, luisg123v commented on attachment_unindex_content/i18n/es_AR.po
> +"Project-Id-Version: Odoo Server 16.0+e\n"
Update only .pot file, the rest will be automatically regenerated by the bots and Weblate

2023-02-26 22:54 UTC, Rodrigosu-Vauxoo commented
Hello @luisg123v , could you review the changes please?

2023-02-27 19:06 UTC, luisg123v commented on attachment_unindex_content/i18n/es_AR.po
> +"Project-Id-Version: Odoo Server 16.0+e\n"
Not fully applied yet, there still are changes to other translation files other than the `.pot`

2023-03-01 21:32 UTC, Rodrigosu-Vauxoo commented
Hello @luisg123v, could you please review the changes?

2023-03-02 02:26 UTC, luisg123v approved these changes
LGTM :+1: 

Hi @moylop260,

Could you review, please?

2023-03-02 14:19 UTC, moylop260 approved these changes
👍

2023-03-02 14:20 UTC, moylop260 commented
/ocabot merge nobump

2023-03-02 14:25 UTC, merged

2023-03-02 15:08 UTC, luisg123v commented
/ocabot migration attachment_unindex_content

2023-03-02 15:10 UTC, luisg123v commented
@moylop260 could you run the command by me, please?

I'm guessing since there are other files modified, the bot doesn't allow me to mark it as migrated.

2023-03-02 15:26 UTC, moylop260 commented
/ocabot migration attachment_unindex_content