[15.0][FIX] *: remove lxml from python depends
OCA/server-tools pull request #2652
Opened 2023-06-06 19:22 UTC by EmilioSerna

Such dependency is already included in Odoo requirements using a pinned
version [1]. Adding here could cause to upgrade the library to an
incompatible version.

[1] https://github.com/odoo/odoo/blob/710a2b2a7af68e8f2f249ef9fc3146f44d3266a5/requirements.txt#L18

2023-06-06 19:26 UTC, hugho-ad approved these changes

2023-06-06 19:27 UTC, legalsylvain approved these changes

2023-06-06 19:27 UTC, EmilioSerna commented
Hi @luisg123v 

Could you please review?

cc @hugho-ad

2023-06-06 19:35 UTC, luisg123v requested changes
Remove also `cryptography`. It was not removed from v14 because it was not in Odoo's main requirements (see https://github.com/OCA/reporting-engine/pull/757#issuecomment-1516833160). But, starting from v15, it is.

2023-06-06 21:45 UTC, EmilioSerna commented
> Remove also `cryptography`. It was not removed from v14 because it was not in Odoo's main requirements (see [OCA/reporting-engine#757 (comment)](https://github.com/OCA/reporting-engine/pull/757#issuecomment-1516833160)). But, starting from v15, it is.

Changes applied

2023-06-06 22:08 UTC, luisg123v requested changes
Combine the two last commits (letsencrypt and the one that removes cryptography from requirements) because they both belong to the same change. Take into account the `requirements.txt` file is autogenerated from module's manifest

2023-06-06 22:13 UTC, EmilioSerna commented
@luisg123v 

Done

2023-06-06 23:53 UTC, luisg123v approved these changes
LGTM :+1: 

@moylop260 could you review, please?

2023-06-07 01:03 UTC, moylop260 commented
/ocabot merge patch

2023-06-07 01:14 UTC, merged

2024-04-05 01:32 UTC, yaazkal commented
I know this is old now, but I wonder why you are keeping `cryptography==2.6.1` anyway in the `requirements.txt` file and in the `auto_backup` module.