16.0 mig base changeset
OCA/server-tools pull request #2663
Opened 2023-06-29 12:41 UTC by MrGigSolutions

2023-06-29 13:03 UTC, StefanRijnhart commented
/ocabot migration base_changeset

2023-06-29 13:26 UTC, StefanRijnhart commented
When logging in with user demo, the access restrictions on ir.model cause an exception:
```
  File "/home/odoo/16.0/parts/odoo/odoo/api.py", line 409, in _model_create_multi
    return create(self, [arg])
  File "/home/odoo/16.0/parts/server-tools/base_changeset/models/base.py", line 80, in create
    if self._changeset_disabled():
  File "/home/odoo/16.0/parts/server-tools/base_changeset/models/base.py", line 111, in _changeset_disabled
    if self._name not in self.models_to_track_changeset():
  File "<decorator-gen-120>", line 2, in models_to_track_changeset
  File "/home/odoo/16.0/parts/odoo/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/16.0/parts/server-tools/base_changeset/models/base.py", line 71, in models_to_track_changeset
    models = self.env["changeset.field.rule"].search([]).mapped("model_id.model")
  File "/home/odoo/16.0/parts/odoo/odoo/models.py", line 5362, in mapped
    recs = recs._fields[name].mapped(recs)
  File "/home/odoo/16.0/parts/odoo/odoo/fields.py", line 1278, in mapped
    self.__get__(first(remaining), type(remaining))
  File "/home/odoo/16.0/parts/odoo/odoo/fields.py", line 1187, in __get__
    record._fetch_field(self)
  File "/home/odoo/16.0/parts/odoo/odoo/models.py", line 3162, in _fetch_field
    self._read(fnames)
  File "/home/odoo/16.0/parts/odoo/odoo/models.py", line 3172, in _read
    self.check_access_rights('read')
  File "/home/odoo/16.0/parts/odoo/odoo/models.py", line 3432, in check_access_rights
    return self.env['ir.model.access'].check(self._name, operation, raise_exception)
  File "/home/odoo/16.0/parts/odoo/odoo/addons/base/models/ir_model.py", line 1893, in check
    raise AccessError(msg)
odoo.exceptions.AccessError: You are not allowed to access 'Models' (ir.model) records.
```

2023-09-09 07:23 UTC, hbrunn requested changes
found a small issue and a few nitpicks. Please also update the screenshots, they are quite dated by now

2023-09-09 07:23 UTC, hbrunn commented on base_changeset/README.rst
> +  and even in 14.0 (in the case of fields for which no value was set yet).
I think it would be helpful anyways to allow integrators to create such labels themselves by adding an element with some specific class and possibly a data property for which field(s) it is the changeset label. But that's a proposal for adding to the roadmap, not to do here

2023-09-09 07:23 UTC, hbrunn commented on base_changeset/models/base.py
> +        if config["test_enable"] and self.env.context.get("test_record_changeset"):
did you consider getting rid of this code using https://github.com/OCA/odoo-test-helper ?

2023-09-09 07:23 UTC, hbrunn commented on base_changeset/models/base.py
> +        can_see = len(self) == 1 and self.user_can_see_changeset
I wonder why this works, isn't self usually empty at this point? Actually, I'd expect the buttons to show up on Azure Interior's [form](http://oca-server-tools-16-0-pr2663-731e5236cd81.runboat.odoo-community.org/web?debug=1#id=14&cids=1&menu_id=142&action=178&model=res.partner&view_type=form) as admin:

![image](https://github.com/OCA/server-tools/assets/2563186/f28efb9f-f3d0-4762-83bc-e17240ba00ca)

with existing [pending changesets](http://oca-server-tools-16-0-pr2663-731e5236cd81.runboat.odoo-community.org/web?debug=1#action=107&model=record.changeset&view_type=list&cids=1&menu_id=4) like 
![image](https://github.com/OCA/server-tools/assets/2563186/7d0252e8-666c-48b7-8293-ebe5c04d6fb3)

2023-09-09 07:23 UTC, hbrunn commented on base_changeset/security/groups.xml
> +            <field name="users" eval="[(4, ref('base.user_root'))]" />
I'd suggest to also add admin here (`base.user_admin`)

2023-09-11 06:45 UTC, StefanRijnhart commented on base_changeset/models/base.py
> +        can_see = len(self) == 1 and self.user_can_see_changeset
Thanks for the review! About this particular comment, there is one change that involves the reference field. The related button is visible on the tab where the field resides:
![image](https://github.com/OCA/server-tools/assets/1033124/8894c9e3-d7e0-4065-a3d2-833099c78552)
All the other changes are on the `street2` field, which is label-lless and therefore falls under the technical gotcha.

2023-09-11 07:06 UTC, hbrunn commented on base_changeset/models/base.py
> +        can_see = len(self) == 1 and self.user_can_see_changeset
oh, I don't mean the labels, that works just fine for me. I'm talking about the smartbutton that's supposed to show up on the form for records with changes on the top right.

Would be good to add a modifier there to hide it when there are no changes.

2023-09-11 07:17 UTC, StefanRijnhart commented on base_changeset/models/base.py
> +        can_see = len(self) == 1 and self.user_can_see_changeset
I see and I agree, thanks for clarifying!

2024-05-07 14:10 UTC, StefanRijnhart commented on base_changeset/README.rst
> +  and even in 14.0 (in the case of fields for which no value was set yet).
Added to the roadmap.

2024-05-07 14:11 UTC, StefanRijnhart commented on base_changeset/models/base.py
> +        if config["test_enable"] and self.env.context.get("test_record_changeset"):
No, the current test mechanism wasn't in the way of the migration.

2024-05-07 14:12 UTC, StefanRijnhart commented on base_changeset/models/base.py
> +        can_see = len(self) == 1 and self.user_can_see_changeset
Fixed the migration (`fields_view_get` -> `get_view`) and added the improvement in a separate commit. I'm hiding the button if there are no changesets in any state, to allow tracking changes that were validated in the past as well.

2024-05-07 14:12 UTC, StefanRijnhart commented on base_changeset/security/groups.xml
> +            <field name="users" eval="[(4, ref('base.user_root'))]" />
Done.

2024-05-13 05:28 UTC, hbrunn approved these changes

2024-05-15 09:33 UTC, houssine78 approved these changes
LGTM

2024-05-15 09:34 UTC, houssine78 commented
Hi @StefanRijnhart I think this PR is ready to be merged :)

2024-05-24 15:23 UTC, victoralmau approved these changes

2024-05-24 16:10 UTC, hbrunn commented
/ocabot merge nobump

2024-05-24 16:24 UTC, merged