[16.0][IMP] module_change_auto_install: also allow using environment variables
OCA/server-tools pull request #2811
Opened 2024-01-18 15:44 UTC by vincent-hatakeyama

2024-03-14 15:36 UTC, legalsylvain approved these changes
makes sense !

2024-04-19 13:40 UTC, houzefa-abba approved these changes

2024-04-19 15:29 UTC, legalsylvain requested changes
Could you add an exemple of how to use environment variable in the configure section, specially for the dict syntax ?

2024-05-13 13:01 UTC, vincent-hatakeyama commented
I added information on how to use the environment variables too.

2024-05-13 18:07 UTC, legalsylvain commented
Thanks !

/ocabot merge minor

2024-05-13 19:43 UTC, legalsylvain commented
@vincent-hatakeyama could you take a look ?

2024-05-17 09:47 UTC, vincent-hatakeyama commented
> @vincent-hatakeyama could you take a look ?

I’ve remove the rst that seems to cause trouble.

2024-05-17 09:53 UTC, legalsylvain approved these changes
/ocabot merge minor

2024-05-17 10:06 UTC, vincent-hatakeyama commented
The tests in error are unrelated, they are from module attachment_synchronize.

2024-05-17 12:50 UTC, legalsylvain commented
@vincent-hatakeyama : waiting for https://github.com/OCA/storage/pull/372

2024-05-28 14:47 UTC, SirAionTech commented
> @vincent-hatakeyama : waiting for [OCA/storage#372](https://github.com/OCA/storage/pull/372)

@legalsylvain it is merged

2024-05-28 14:48 UTC, legalsylvain commented
Thanks ! 

/ocabot merge patch

2024-05-28 14:50 UTC, SirAionTech approved these changes
Thanks for the PR!
Only code review

2024-05-28 15:22 UTC, legalsylvain commented
/ocabot rebase

2024-05-28 15:23 UTC, legalsylvain commented
@vincent-hatakeyama could you rebase ?

2024-05-28 15:23 UTC, SirAionTech requested changes

2024-05-28 15:23 UTC, SirAionTech commented on module_change_auto_install/readme/CONFIGURE.rst
> +   :emphasize-lines: 1
```suggestion
```
This is probably the line causing the merge fails, can it be removed?

2024-05-28 15:29 UTC, vincent-hatakeyama commented
> @vincent-hatakeyama could you rebase ?

I’ve rebased after removing the line emphasis.

2024-05-28 15:37 UTC, SirAionTech approved these changes

2024-05-28 16:14 UTC, legalsylvain commented
Merge, fourth try...

/ocabot rebase

2024-05-28 18:58 UTC, legalsylvain commented
/ocabot merge patch

2024-05-28 19:06 UTC, merged