[16.0][FIX] auto_backup: do not fail if directory exists
OCA/server-tools pull request #2939
Opened 2024-05-11 10:54 UTC by NL66278

2024-05-28 14:03 UTC, SirAionTech requested changes
Thanks for the PR!
Only code review

2024-05-28 14:03 UTC, SirAionTech commented on auto_backup/models/db_backup.py
> +                                remote.makedirs(rec.folder, exist_ok=True)
```suggestion
                                remote.makedirs(rec.folder)
```
Looks like a `pysftp.Connection` does not have this parameter 
![image](https://github.com/OCA/server-tools/assets/143788994/9421952b-1773-49c8-8995-04a0f93c4a8c)

(from https://pysftp.readthedocs.io/en/release_0.2.9/pysftp.html#pysftp.Connection.makedirs)

2024-05-28 14:03 UTC, SirAionTech commented on auto_backup/tests/test_db_backup.py
> +                    conn.makedirs.assert_called_once_with(rec_id.folder, exist_ok=True)
```suggestion
                    conn.makedirs.assert_called_once_with(rec_id.folder)
```
see previous comment.
Could you please add a test to check for the change to local backups instead?

2024-05-28 14:30 UTC, NL66278 commented
@SirAionTech Thank you for your review and suggestions. I limited the fix to the local back-up now.

2024-05-28 14:35 UTC, SirAionTech approved these changes

2024-08-21 15:34 UTC, sergiocorato approved these changes

2025-09-17 12:48 UTC, StefanRijnhart commented
Included in merged https://github.com/OCA/server-tools/pull/3089, so closing this one.

2025-09-17 12:48 UTC, closed without merging

2025-09-17 12:51 UTC, StefanRijnhart commented
The merged PR still has the flaw that was corrected during the review of this PR. Can you have a look at https://github.com/OCA/server-tools/pull/3217 to confirm this PR is the right fix for that?