[18.0][MIG] scheduler_error_mailer
OCA/server-tools pull request #3084
Opened 2024-10-17 07:25 UTC by astirpe

2024-11-26 11:37 UTC, CasVissers-360ERP commented on scheduler_error_mailer/models/ir_cron.py
> +    def _callback(self, cron_name, server_action_id, job_id):
@astirpe the original method has changed, can you check?

2025-02-07 09:43 UTC, StefanRijnhart commented
/ocabot migration scheduler_error_mailer

2025-02-07 09:47 UTC, StefanRijnhart approved these changes
Tests are fixed in https://github.com/OCA/server-tools/pull/3190. Please rebase once that one is merged.

2025-02-07 11:16 UTC, astirpe commented
@StefanRijnhart I will, thank you!

2025-02-07 14:35 UTC, astirpe commented
rebased

2025-02-07 14:40 UTC, StefanRijnhart commented on scheduler_error_mailer/models/ir_cron.py
> +    def _callback(self, cron_name, server_action_id, job_id):
Please update your review @CasVissers-360ERP

2025-03-24 10:35 UTC, CRogos requested changes
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-18.0

Squash administrative commits (if any) with the previous commit for reducing commit noise. Check https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate for details.
Here are some examples:
![image](https://github.com/user-attachments/assets/a57fdc90-8f18-420e-b403-f61931333285)

Maybe we could also improve the test and test "def _callback" instead of "def _handle_callback_exception"?

2025-03-24 10:35 UTC, CRogos commented on scheduler_error_mailer/models/ir_cron.py
> +            self._handle_callback_exception(cron_name, server_action_id, e)
Is it intended that the exception is not raised again?

maybe we also should move the _handle_callback_exception in this method when odoo also removed it?

2025-03-24 10:36 UTC, CRogos commented on scheduler_error_mailer/tests/test_scheduler_error_mailer.py
> +class TestSchedulerErrorMailer(TransactionCase):
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-18.0
Use BaseCommon as base test class to reduce overhead from tracking and boost the test suite.

2025-04-10 14:13 UTC, CRogos commented
@astirpe are you still working on this?

2025-04-10 15:08 UTC, astirpe commented
@CRogos Thank you for your review! I'm very busy with projects, I could continue with this when I can find some time. Sorry

2025-04-12 07:55 UTC, astirpe commented on scheduler_error_mailer/models/ir_cron.py
> +            self._handle_callback_exception(cron_name, server_action_id, e)
I think this is correct as it is. The Odoo base _callback() only logs any exception, not raising.
And I honestly can't see any reason for moving _handle_callback_exception() inside here.

2025-04-12 18:31 UTC, astirpe commented on scheduler_error_mailer/tests/test_scheduler_error_mailer.py
> +class TestSchedulerErrorMailer(TransactionCase):
Done, thanks!

2025-04-14 06:34 UTC, astirpe commented on scheduler_error_mailer/models/ir_cron.py
> +            self._handle_callback_exception(cron_name, server_action_id, e)
I checked again and indeed the Odoo base _callback() is raising the exception.
I added this commit to re-raise it again:
https://github.com/OCA/server-tools/pull/3084/commits/31459b46d67fbce434394940690ded476b9f07a2

2025-04-16 08:10 UTC, StefanRijnhart commented
@CRogos Is it alright for you now?

2025-04-16 09:09 UTC, StefanRijnhart commented
Oh, we're getting errors because the mail template body is no longer valid due to the ir.cron datamodel changes. @astirpe would you consider taking https://github.com/astirpe/server-tools/pull/1?

2025-04-16 09:31 UTC, astirpe commented
Thank you @StefanRijnhart !

2025-04-16 09:48 UTC, CRogos requested changes
Can you squash your latest changes with the Migration commit and also cleanup the commits above according to the migration guide?

2025-04-16 09:48 UTC, CRogos commented on scheduler_error_mailer/models/ir_cron.py
> +            raise e
Can't we write raise without the e to reraise?

2025-04-16 09:48 UTC, CRogos commented on scheduler_error_mailer/migrations/18.0.1.0.0/post-migration.py
Are you sure this is the best option?

Couldn't we just call load_data with the ir_cron_email_tpl.xml file?
https://github.com/OCA/openupgradelib/blob/37cc7eeb1383fbe7c3d5cd2666af3b73338a90cd/openupgradelib/openupgrade.py#L292

Something like this:
https://github.com/OCA/account-financial-reporting/commit/8ba049e8

2025-04-16 10:16 UTC, StefanRijnhart commented on scheduler_error_mailer/migrations/18.0.1.0.0/post-migration.py
That would be equivalent to calling `reset_template` on the template, but it would reset other fields as well such as subject and recipients which are customized in our setups. Also, this bit takes care to reset the body in each language (as per code taken from `reset_template`).

2025-04-16 10:19 UTC, StefanRijnhart commented on scheduler_error_mailer/migrations/18.0.1.0.0/post-migration.py
For reference: code is based on https://github.com/odoo/odoo/blob/18.0/addons/mail/models/template_reset_mixin.py#L70-L93

2025-04-16 10:36 UTC, StefanRijnhart commented
Apologies @astirpe, it turns out that in migrated databases the template_fs of the template might not be set, so here is https://github.com/astirpe/server-tools/pull/2. And please rebase and squash all migration commits as @CRogos suggests.

2025-04-16 10:49 UTC, astirpe commented
I will do the rebase and squash, thanks!

2025-04-16 12:13 UTC, CRogos commented on scheduler_error_mailer/models/ir_cron.py
> +        raise UserError(_("Task failure with UID = %d.") % self._uid)
_ should also be replaced

`raise UserError(self.env._("Task failure with UID = %(uid)d.", uid=self._uid))`

2025-04-16 18:13 UTC, astirpe commented on scheduler_error_mailer/models/ir_cron.py
> +            raise e
Yes, done

2025-04-16 19:29 UTC, CRogos commented on scheduler_error_mailer/models/ir_cron.py
> +        raise UserError(_("Task failure with UID = %(uid)d."), uid=self._uid)
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-18.0

You can replace the call to translate a string (_) with self.env._ for getting some performance improvement in some cases. See https://github.com/odoo/odoo/pull/174844.

2025-04-29 16:07 UTC, CRogos requested changes

2025-04-29 16:07 UTC, CRogos commented on scheduler_error_mailer/models/ir_cron.py
> +        raise UserError(_("Task failure with UID = %(uid)d."), uid=self._uid)
@astirpe  are you still working on this

```suggestion
        raise UserError(self.env._("Task failure with UID = %(uid)d.", uid=self._uid))
```

2025-04-29 16:07 UTC, CRogos commented on scheduler_error_mailer/models/ir_cron.py
> +from odoo import _, api, fields, models
```suggestion
from odoo import api, fields, models
```

2025-05-06 14:01 UTC, CRogos commented
@astirpe are you still working on this?

2025-05-12 07:00 UTC, astirpe commented on scheduler_error_mailer/models/ir_cron.py
> +        raise UserError(_("Task failure with UID = %(uid)d."), uid=self._uid)
Done, thanks!

2025-05-12 08:51 UTC, CRogos commented
There are still some commits which should be squashed: 

https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate
![image](https://github.com/user-attachments/assets/56db6b90-581e-4512-a258-58ab044880fb)

2025-06-26 16:12 UTC, CRogos commented
@astirpe could you do the squashing? I think we can merge afterwards.

2025-06-27 06:57 UTC, astirpe commented
@CRogos squashed, thanks!

2025-06-27 07:20 UTC, CRogos approved these changes

2025-06-27 07:34 UTC, StefanRijnhart commented
/ocabot merge nobump

2025-06-27 07:41 UTC, merged