mgmtsystem_kpi rename to kpi
OCA/server-tools pull request #543
Opened 2016-09-06 12:10 UTC by naousse

2016-09-06 16:52 UTC, max3903 commented on kpi/README.rst
> +
@naousse Replace this usage section (from the nonconformity module) with the link to the video I sent you.

2016-09-06 16:52 UTC, max3903 commented on kpi/README.rst
> +* Automatically add responsible_user_id._uid, manager_user_id._uid, author_user_id._uid to chatter
@naousse Wrong content here. Please add the remaining work to be done with the color stuff.

2016-09-06 16:54 UTC, max3903 commented on kpi/__openerp__.py
> +        'data/mgmtsystem_kpi.xml',
@naousse Please remove `mgmtsystem_` from every file names.

2016-09-06 22:53 UTC, naousse commented
**base.group_hr_user** is the employee user group i have and it is defined here:
/home/odoo/odoo-dev/odoo/addons/hr/security/hr_security.xml.
Without the hr dependance the system output that that id is missed and when i add the hr dependance, everything works fine.

2016-09-07 01:05 UTC, max3903 commented
@naousse This is the wrong group. The `Employee` group (base.group_user) is created here:
https://github.com/odoo/odoo/blob/9.0/openerp/addons/base/security/base_security.xml#L24

2016-09-07 12:41 UTC, naousse commented
Everything is ok now

2016-09-07 16:29 UTC, max3903 commented
@naousse Please review: https://github.com/naousse/server-tools/pull/1

2016-09-07 16:34 UTC, naousse commented
:+1:  
I haven't paid attention about that

2016-09-07 17:04 UTC, max3903 commented
Depends on #513

2016-09-08 13:26 UTC, max3903 commented
@naousse Can you rebase please?

2016-09-09 14:19 UTC, max3903 commented
@naousse Can you rebase again please? Runbot should be usable now.

2016-09-09 22:08 UTC, max3903 commented
@naousse Few UI changes:

# KPI
- [ ] Hide the company field on the list and form view. Should be displayed to multi_company group only.

# Thresholds
- [ ] Hide the company field on the list and form view. Should be displayed to multi_company group only.
- [ ] Move the company field on the same line as the name field
- [ ] Add the label for the name
- [ ] Hide the company field on the list view of Ranges and KPIs. Should be displayed to multi_company group only.

# Ranges
- [ ] Hide the company field on the list and form view. Should be displayed to multi_company group only.
- [ ] Add the label for the name and color
- [ ] Name and company field should be on the same line
- [ ] Type of min and max takes the whole line. Half of it is fine.
- [ ] Fixed value and the datasource should be on the same line as the type.
- [ ] Hide the company field on the list view of Thresholds. Should be displayed to multi_company group only.

2016-09-17 16:12 UTC, max3903 commented
@naousse There is one error on Runbot:
`openerp.addons.base.ir.ir_cron:139 _callback Model `mgmtsystem.kpi` does not exist.`

2016-09-19 14:06 UTC, max3903 approved these changes
:+1:

2016-09-20 13:15 UTC, elicoidal commented on kpi/README.rst
> +server-tools/issues/new?body=module:%20
Remove this line following newest templates

2016-09-20 13:15 UTC, elicoidal commented on kpi/README.rst
> +Installation
remove this section

2016-09-20 13:16 UTC, elicoidal commented on kpi/README.rst
> +To contribute to this module, please visit http://odoo-community.org.
https

2016-09-20 13:16 UTC, elicoidal commented on kpi/__openerp__.py
>      "demo": [],
remove these 2 keys

2016-09-20 13:18 UTC, elicoidal commented on kpi/models/kpi.py
> +            # obj.history_ids = history_obj.search([("kpi_id", "=", obj.id)])
remove dead code

2016-09-20 13:19 UTC, elicoidal commented on kpi/models/kpi.py
> +            # res = self.compute_kpi_value()
remove dead code

2016-09-20 13:19 UTC, elicoidal commented on kpi/models/kpi_category.py
> +# -*- coding: utf-8 -*-
Can you use short headers

2016-09-20 13:20 UTC, elicoidal commented on kpi/models/kpi_threshold.py
> +                result[obj.id] = ("2 of your ranges are overlapping! Please "
s/2/Two

2016-09-20 13:57 UTC, elicoidal requested changes

2016-09-21 14:24 UTC, naousse commented on kpi/models/kpi_threshold.py
> +                result[obj.id] = ("2 of your ranges are overlapping! Please "
@elicoidal I made changes base on your review. You can check if everything is correct. Please I don't understand what you mean here

2016-09-22 01:00 UTC, elicoidal commented on kpi/models/kpi_threshold.py
> +                result[obj.id] = ("2 of your ranges are overlapping! Please "
@naousse In English (and in French too actually), you normally do not start a sentence with a number but number writen in plain English hence my suggestion to change "2"  by "Two".

2016-09-28 20:47 UTC, max3903 commented
@elicoidal Can you update your review please?

2016-09-28 20:47 UTC, max3903 commented
Ping @dreispt

2016-09-29 05:08 UTC, elicoidal reviewed
I think there has been a misunderstanding about the headers. Please check the example.
Note that you should have copyright notices in xml files as well (check: https://github.com/OCA/maintainer-tools/blob/master/template/module/data/model_name_data.xml#L2)

2016-09-29 05:08 UTC, elicoidal commented on kpi/models/__init__.py
> +# -*- coding: utf-8 -*-
Don't you need copyright notice?

2016-09-29 05:08 UTC, elicoidal commented on kpi/models/kpi.py
> +# -*- coding: utf-8 -*-
Don't you need copyright notice?

2016-09-29 05:08 UTC, elicoidal commented on kpi/models/kpi_category.py
> +# -*- coding: utf-8 -*-
Sorry: there must have been a misunderstanding: can you use short headers similar to https://github.com/OCA/maintainer-tools/blob/master/template/module/__openerp__.py#L1 including your actual information?

2016-09-29 05:08 UTC, elicoidal commented on kpi/views/kpi.xml
> +                        <filter name="active" icon="terp-document-new" domain="[('active','=',True)]" string="Active" help="Only active KPIs are computed by the scheduler based on the periodicity con
Can you try to improve the format of the line for readability (like above one)

2016-10-13 15:17 UTC, max3903 commented
@naousse Can you fix based on @elicoidal latest comments? Thanks!

2016-10-23 17:46 UTC, dreispt approved these changes
LGTM

2016-10-23 17:46 UTC, dreispt commented on kpi/__init__.py
> +# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
IMO copyright is attributed to original authors only, and contributors should not be included on authorship and copyright attribution.

2016-10-24 17:52 UTC, max3903 commented
@elicoidal Can you update your review? Copyrights headers are correct now.

2016-10-25 02:16 UTC, elicoidal commented on kpi/__init__.py
> +# Copyright <YEAR(S)> Savoir-faire Linux <https://www.savoirfairelinux.com/>
Please update the year

2016-10-25 02:17 UTC, elicoidal commented on kpi/models/kpi_threshold.py
> +                                _("Two of your ranges are overlapping!"),
Avoid "!" in error message, it makes users uncomfortable

2016-10-25 02:19 UTC, elicoidal commented
Please fix the copyright then :+1:  on my side

2016-10-26 13:01 UTC, naousse commented
@max3903 Please can you provide the right year for the copyright?

2016-10-26 14:42 UTC, max3903 commented
@naousse `2012 - Now`

2016-12-02 13:42 UTC, dreispt commented
@elicoidal fix request was done - merging!

2016-12-02 13:43 UTC, merged