[10.0][MIGRATION] Migrated module 'date_range' to V10
OCA/server-tools pull request #567
Opened 2016-10-07 13:12 UTC by espo-tony

2016-10-08 11:30 UTC, pedrobaeza approved these changes

2016-10-08 13:48 UTC, lmignon requested changes

2016-10-08 13:48 UTC, lmignon commented on date_range/README.rst
> +* Andrea Stirpe <a.stirpe@onestein.nl>
IMO this kind of changes doesn't justify 2 new contributors. But thank you for the migration.

2016-10-09 19:42 UTC, Garamotte approved these changes
Same remark as @lmignon 
Otherwise :+1:

2016-10-10 07:02 UTC, espo-tony commented
@lmignon , @sylvain-garancher 
Sorry for updating the contributor list without a proper reason; I just corrected my mistake.

2016-10-10 07:17 UTC, adrienpeiffer approved these changes
:+1:

2016-10-10 07:20 UTC, lmignon approved these changes

2016-10-10 07:23 UTC, merged

2016-10-10 07:27 UTC, lmignon commented
@espo-tony You're welcome :smirk: Your name is in the commit history and you have done a valuable work! I just try to avoid that the Contributor's list become a list of all commiters. Nevertheless if you enhance the module (technically / functionally) I'll be happy to see your name in this list.