[MIG] migrate dbfilter_from_header to 10.0
OCA/server-tools pull request #571
Opened 2016-10-12 12:03 UTC by JosDeGraeve

I have also removed the ability to use HTTP_X_OPENERP_DBFILTER

Due to the fact that with odoo v10, all legacy openerp naming has been removed.

2016-10-13 05:48 UTC, hbrunn approved these changes

2016-10-13 06:17 UTC, pedrobaeza commented on dbfilter_from_header/README.rst
>  This addon has to be loaded as server-wide module.
@antespi can you tell us here the instructions for Apache or haproxy to be included?

2016-10-13 06:18 UTC, pedrobaeza requested changes
Please adapt bug tracker section to the new template where the link is removed: https://raw.githubusercontent.com/OCA/maintainer-tools/master/template/module/README.rst

2016-10-14 16:12 UTC, pedrobaeza approved these changes

2016-10-14 16:25 UTC, JosDeGraeve commented on dbfilter_from_header/README.rst
>  This addon has to be loaded as server-wide module.
I have added the configuration statemetns for Apache and Caddy.
I'm not familiar enough with HAproxy.

2016-10-17 12:37 UTC, RoelAdriaans approved these changes

2016-10-17 12:39 UTC, merged