Mig to v10
OCA/server-tools pull request #598
Opened 2016-11-10 15:13 UTC by JayVora-SerpentCS

2016-11-11 06:46 UTC, nhomar commented
Thanks @JayVora-SerpentCS 

One quick quiestion.

I think the button in the screen that create the action to comply with the >v8.0 usability standard due to the fact that is an "action" button and not a "link" buttton should be in the top of the screen.

I know this is a silly question but I personally think we all will be more happy if we migrate to 10.0 with this little change..

![](http://screenshots.vauxoo.com/nhomar/Selection_046.png)

Can You? or do you prefer I make a separate PR?

2016-11-11 08:06 UTC, jgrandguillaume approved these changes
Hi @JayVora-SerpentCS 

Thanks for this great module ! 

Tested and works well :+1: 

Regards,

Joël

2016-11-11 15:16 UTC, atchuthan commented
Found a strange bug when I tried to test the functionality in Runbot

URL: http://3271979-598-6ab5a8.runbot1.odoo-community.org/

Partner Mass editing
![image](https://cloud.githubusercontent.com/assets/4667326/20219350/099e7f44-a84f-11e6-8fb0-047e4779b52b.png)

Mass editing window after selecting 2 partners (ASUSTeK/Test1 & ASUSTeK/Test2)
![image](https://cloud.githubusercontent.com/assets/4667326/20219390/36642ab0-a84f-11e6-9985-af44b2ac93b1.png)

Mass editing window after selecting all partners
![image](https://cloud.githubusercontent.com/assets/4667326/20219447/76ca007a-a84f-11e6-9162-4e6d9f4921b4.png)

2016-11-11 16:50 UTC, pedrobaeza commented
@JayVora-SerpentCS, thanks for maintaining this module. Please follow full 10.0 migration guide: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0#tasks-to-do-in-the-migration and take care about the comments.

You also need to bring the latest changes of the 9.0 branch. For example https://github.com/OCA/server-tools/commit/65a1579e99ff623bf39e3e081baa9d31f0a62736. This is done with https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0#technical-method-to-migrate-a-module-from-90-to-100-branch

2016-12-09 13:54 UTC, JayVora-SerpentCS commented
@pedrobaeza how to bring https://github.com/OCA/server-tools/commit/65a1579e99ff623bf39e3e081baa9d31f0a62736?

2016-12-09 15:58 UTC, pedrobaeza commented
Do:
```
git remote update
git cherry-pick 65a1579
```

2016-12-09 21:32 UTC, njeudy approved these changes
Tested and code review

👍

2016-12-10 10:43 UTC, antoniocanovas approved these changes
LGTM, Tested on runbot.

2016-12-10 10:53 UTC, pedrobaeza commented
The missing commits are still not brought and there's a comment unattended.

2016-12-10 12:05 UTC, JayVora-SerpentCS commented
Agreed, working on them soon.
Thanks.

2016-12-28 22:48 UTC, ovnicraft commented
Hi @JayVora-SerpentCS any updates for this ?

2016-12-29 06:51 UTC, JayVora-SerpentCS commented
Cherrypicked Pedro's commit. now working on the other 2 comments.

2016-12-29 10:45 UTC, JayVora-SerpentCS commented
@nhomar covered.
![screenshot from 2016-12-29 16-13-45](https://cloud.githubusercontent.com/assets/5909386/21542168/e76fe774-cde1-11e6-8e6d-54c27855e8ef.png)
@atchuthan I tried various scenarios, but did not manage to reproduce. Would you please retry?
Thanks.

2016-12-29 13:49 UTC, ovnicraft commented
Tested on runbot and working ok 👍

2017-01-10 17:42 UTC, ovnicraft commented
There is no report to reproduce the bug mentioned by @atchuthan, IMO this is ready to merge.

2017-01-16 16:52 UTC, JonathanNEMRY requested changes
Hi! Great work! I just made a PR on your branch to add setuptools. Otherwise :+1: 
https://github.com/JayVora-SerpentCS/server-tools/pull/1

2017-01-17 12:56 UTC, JonathanNEMRY approved these changes
:+1:

2017-01-17 12:57 UTC, pedrobaeza commented
Squashing and merging. Thanks for the work.

2017-01-17 13:25 UTC, pedrobaeza commented
@JayVora-SerpentCS, I'm missing these two important pieces for improving the module that has been done in v8:

* https://github.com/OCA/server-tools/commit/444242489199b5a50213e2f79791d60aad00949d
* https://github.com/OCA/server-tools/commit/09732a891c96d625b31b631995f3adf3d2aff4f3

Can you please adapt the code for this version?

2017-01-17 13:26 UTC, pedrobaeza requested changes
Due to above comment

2017-01-18 08:52 UTC, JayVora-SerpentCS commented
Processed.

2017-01-18 13:18 UTC, atchuthan approved these changes
@JayVora-SerpentCS 
Sorry for the late follow-up.  I couldn't reproduce the error in latest runbot.  So, :+1: my vote

2017-02-13 17:31 UTC, pedrobaeza commented
@JayVora-SerpentCS you have the bad habit of overwriting author commits with yours. Please respect the credits of the person who added the last 2 commits. What you have to do is cherry-picking commits as is, solving any possible conflict, and then adding a new commit with the changes you need to do for adapting to v10 (excluding conflicts already solved).

Please also see for the runbot warning that appears (I have launched a rebuild for seeing the log). When done, I'll merge.

2017-02-14 05:29 UTC, JayVora-SerpentCS commented
@pedrobaeza , no we did not overwrite anyone's commit. We cherry picked only.
We will check what's overwritten. If not, we will propose a clean merge.

2017-02-14 06:31 UTC, JayVora-SerpentCS commented
Help me understand better, the cherrypicked commits are already linked and referred : https://github.com/OCA/server-tools/pull/598/commits/6c7e2402a750579f07e826246efaca547bac5238
If you think cleaning is better, I will clean the proposal and push in single commit after cherrypicking again.

2017-02-14 08:18 UTC, pedrobaeza commented
This is not cherry-picking, Jay. A cherry-pick is that you bring the commits as is, not integrating them in another commit with you as the author of the full diff:

![seleccion_001](https://cloud.githubusercontent.com/assets/7165771/22920608/3c4439de-f296-11e6-9fec-a9527884ae5b.png)

A correct cherry-pick would show in the commit list both commits with the corresponding authors, something like:

![seleccion_002](https://cloud.githubusercontent.com/assets/7165771/22920674/9b4f72d6-f296-11e6-86d0-5a0d47e6a35c.png)

2017-02-14 08:32 UTC, mourad-ehm commented
Code review :+1:

2017-02-14 09:03 UTC, LoisRForgeFlow requested changes
This error pops when trying to add items to a new mass.object record (testing on runbot):
![image](https://cloud.githubusercontent.com/assets/23449160/22922084/82d76d20-f29c-11e6-8594-653fc1f64062.png)

Also, please attend runbot warning: <code>WARNING openerp_test odoo.fields: Field mass.object.name: parameter 'select' is no longer supported; use 'index' instead.</code>

2017-02-15 08:00 UTC, JayVora-SerpentCS commented
@pedrobaeza You are a nice teacher along with Google! I learned well now the cherry-picking. Earlier commits were squashed and hence it would reflect we ate them, which we actually did not.
I rebased the PR nicely now.
@lreficent Sorry I do not see a reason to face the error. Any detailed traceback possible?
Thanks.

2017-02-15 08:58 UTC, AaronHForgeFlow requested changes
When creating a mass editing record on runbot I'm getting an error:
![image](https://cloud.githubusercontent.com/assets/19620251/22967079/44cc07c4-f365-11e6-8a7e-9e61d5828074.png)

2017-02-15 09:11 UTC, lreficent commented
@JayVora-SerpentCS I get the error when trying to create a Mass Editing record as usual and trying to add the fields. I have just tested on local right now, same error raises. Aren't you getting the error? Maybe it is my fault but I think it is worth that you test it at least functionally in a moment to test whether it pops for you or not. Really appreciate the effort, thanks!

2017-02-15 09:40 UTC, JayVora-SerpentCS commented
Will check definitely soon and fix if such happens.

2017-02-16 06:17 UTC, JayVora-SerpentCS commented
@aheficent @lreficent True that, made sure no loop hole stays now, edited the domain and fixed.
Thanks.

2017-02-16 08:36 UTC, aheficent commented on mass_editing/models/mass_object.py
> +        print args
I guess this is here for debugging and you will remove it. Also, this is causing travis to fail.

2017-02-16 10:05 UTC, JayVora-SerpentCS commented on mass_editing/models/mass_object.py
> +        print args
For sure, thanks, managed. Had pushed in a hurry :)

2017-02-16 11:20 UTC, AaronHForgeFlow approved these changes
:+1: Thanks

2017-02-16 15:13 UTC, LoisRForgeFlow approved these changes
Works fine now. Thank you!

2017-02-16 15:15 UTC, pedrobaeza commented
@JayVora-SerpentCS, if you want to avoid the forgotten print and pylint/flake8 errors locally, you can install the GIT pre-commit we prepare in MQT: https://github.com/OCA/maintainer-quality-tools/tree/master/git

2017-02-17 08:49 UTC, JayVora-SerpentCS commented
@pedrobaeza I am using pycharm with pep8 and pyflakes extension already.
I will install the precommit too. Thanks.

2017-02-20 12:47 UTC, pedrobaeza approved these changes
Well, finally the history is still no clean (as the other commits don't contain diff), but I don't want to block more time, so I finally squash.

2017-02-20 12:47 UTC, merged