[ADD] 8.0 - New module 'base_user_role' to manage user roles efficiently
OCA/server-tools pull request #608
Opened 2016-11-15 13:40 UTC by sebalix

Note : we are using this module on version 6.0, 7.0 and 8.0 I just added the support for dates recently on the 8.0 version. I'll migrate it to 9.0 and 10.0 soon.

User roles
========

This module was written to extend the standard functionality regarding users and groups management. It helps creating well-defined user roles and associating them to users.

It can become very hard to maintain a large number of user profiles over time, juggling with many technical groups. For this purpose, this module will help you to:

  * define functional roles by aggregating low-level groups,
  * set user accounts with the predefined roles (roles are cumulative),
  * update groups of all relevant user accounts (all at once),
  * ensure that user accounts will have the groups defined in their roles (nothing more, nothing less). In other words, you can not set groups manually on a user as long as there is roles configured on it,
  * activate/deactivate roles depending on the date (useful to plan holidays, etc)
  * get a quick overview of roles and the related user accounts.

That way you make clear the different responsabilities within a company, and are able to add and update user accounts in a scalable and reliable way.

Configuration
=============

To configure this module, you need to go to *Configuration / Users / Roles*, and create a new role. From there, you can add groups to compose your role, and then associate users to it.

2016-11-15 13:51 UTC, sebalix commented
About Travis: flake8 errors and tests failure not related to this module.

2016-11-16 06:58 UTC, jcdrubay commented
Very good contribution (high quality of code, useful, well documented).
I hope it can be reviewed and merged soon :+1:

2016-11-16 07:33 UTC, lasley requested changes
This is awesome, thanks @sebalix 

Code, no test. Comments inline

2016-11-16 07:33 UTC, lasley commented on base_user_role/__openerp__.py
> +    'depends': [
You can remove this key. `base` dependency is implicit.

2016-11-16 07:33 UTC, lasley commented on base_user_role/models/role.py
> +    @api.depends('line_ids')
`line_ids.user_id`

2016-11-16 07:33 UTC, lasley commented on base_user_role/models/role.py
> +        if users:
There shouldn't be need for this guard, mapped will just return an empty Recordset that should work with the other method just fine due to record loop

2016-11-16 07:33 UTC, lasley commented on base_user_role/models/role.py
> +    is_active = fields.Boolean(u"Active", compute='_compute_is_active')
`active` is the Odoo norm for this col - although I'm with you on prefixing bool cols with linking verbs like `is`, `has`, etc. It also comes with some defaults filters and such, so makes it worth using despite the hurt to naming OCD

That said, it also needs to be `store=True` to allow all of that

2016-11-16 07:33 UTC, lasley commented on base_user_role/models/user.py
> +    @api.depends('role_line_ids')
role_line_ids.role_id

2016-11-16 07:36 UTC, lasley commented
Oh please also check Travis and Runbot 😉

2016-11-16 07:50 UTC, jcdrubay commented on base_user_role/security/ir.model.access.csv
> +access_res_users_role,access_res_users_role,model_res_users_role,"base.group_erp_manager",1,1,1,1
From travis https://travis-ci.org/OCA/server-tools/jobs/176051212#L1703

> The model res.users.role.line has no access rules, consider adding one. E.g. 

`access_res_users_role_line,access_res_users_role_line,model_res_users_role_line,"base.group_erp_manager",1,0,0,0`

2016-11-16 07:51 UTC, sebalix commented
Thank you for the review, I'll fix these points soon

2016-11-16 08:51 UTC, pedrobaeza commented on base_user_role/__openerp__.py
> +    'depends': [
No, you should depend on your module at least in base, but base is implicit when depending on other module.

2016-11-16 17:54 UTC, sebalix commented on base_user_role/models/role.py
> +    is_active = fields.Boolean(u"Active", compute='_compute_is_active')
Indeed, but I was unable to set a working `domain` on the XML views to display all the lines (as we don't want to hide them from the administrator in any case, we just want to filter them when setting groups). If I set the domain on the Python field, it works fine, but then it does not dispense to filter the lines in the `ResUsers.set_groups_from_roles` method. And as I've seen no benefit to use the standard `active` field I ended up adding my own.

2016-11-17 09:08 UTC, sebalix commented on base_user_role/security/ir.model.access.csv
> +access_res_users_role,access_res_users_role,model_res_users_role,"base.group_erp_manager",1,1,1,1
Fixed

2016-11-17 09:09 UTC, sebalix commented on base_user_role/models/role.py
> +    is_active = fields.Boolean(u"Active", compute='_compute_is_active')
Or I could rename it to 'is_enabled'?

2016-11-17 12:56 UTC, susport commented on base_user_role/models/role.py
> +    date_from = fields.Date(u"From")
Date from may be default the date now of the create moment.
Good contribution.
👍

2016-11-17 13:06 UTC, sebalix commented on base_user_role/models/role.py
> +    date_from = fields.Date(u"From")
Dates are optional, no dates = role activated immediately

2016-11-17 16:33 UTC, lasley commented on base_user_role/models/role.py
> +    is_active = fields.Boolean(u"Active", compute='_compute_is_active')
I like the `is_enabled` ideal - it is far enough away from `active` that people won't be trying to change it all the time. I know I would have probably done this during a migration had I not already gotten the reasoning behind it.

2016-11-18 11:55 UTC, sebalix commented on base_user_role/models/role.py
> +    is_active = fields.Boolean(u"Active", compute='_compute_is_active')
It's done!

2016-11-18 13:12 UTC, sebalix commented
I think all the points are fixed.

2016-11-18 17:42 UTC, lasley commented
Travis is still mad 🔴

2016-11-18 20:46 UTC, sebalix commented
You mean I have to fix lint errors of others modules in this one? Tests fail on `fetchmail_notify_error_to_sender`.

2016-11-18 20:54 UTC, lasley approved these changes
Hmm yeah ok the build looks broken on 8.0 branch in the same way, so you are correct that we should not be fixing it here.

2016-11-19 18:21 UTC, sebalix commented
I fixed the other modules in #616 to get green builds.

2016-11-19 22:54 UTC, sebalix commented
Rebased

2016-11-20 12:06 UTC, sbidoul commented
@adrienpeiffer you should have a look at this.

2016-12-08 13:04 UTC, andhit-r commented
Tested functionality on runbot :+1:

2016-12-09 02:26 UTC, andhit-r commented
@mikevhe18 @azmimr67 you guys should take a look at this PR and help review

2016-12-09 05:45 UTC, lasley commented
We're approved for merge. @sebalix - do you prefer to squash your own commits or would you rather me do it? I don't think I've gotten this preference from you yet, but sorry if I'm double asking.

2016-12-09 08:22 UTC, sebalix commented
@lasley You can squash them, no trouble

2016-12-09 17:06 UTC, merged

2016-12-09 17:07 UTC, lasley commented
Thanks for the awesome new module @sebalix! Do you have any plans to migrate it forward?

2016-12-09 21:01 UTC, sebalix commented
@lasley Thank you! Yes, I plan to migrate it to v9 (see #641) and v10 right after.