[9.0] MIG auth_brute_force
OCA/server-tools pull request #663
Opened 2016-12-21 15:53 UTC by nicomacr

2016-12-27 15:26 UTC, jjscarafia approved these changes
Tested locally

2017-02-17 15:54 UTC, nicomacr commented
ping...
Any news with this?

2017-05-04 19:00 UTC, pedrobaeza commented
@chienandalu @luismontalba, can you review?

2017-05-04 19:25 UTC, lasley requested changes
Thanks @nicomacr - comments inline

2017-05-04 19:25 UTC, lasley commented on auth_brute_force/__openerp__.py
> +##############################################################################
Please switch to [shortened header](https://github.com/OCA/maintainer-tools/blob/master/template/module/__openerp__.py#L3) for all files

2017-05-04 19:25 UTC, lasley commented on auth_brute_force/controllers/controllers.py
> +            cursor.commit()
[Never commit the transaction.](https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#never-commit-the-transaction) Why will a savepoint not work? Or maybe a subtransaction?

2017-05-04 19:25 UTC, lasley commented on auth_brute_force/controllers/controllers.py
> +    def web_login(self, redirect=None, **kw):
It would be awesome if we had some test cases for this.

2017-05-04 19:25 UTC, lasley commented on auth_brute_force/controllers/controllers.py
> +            max_attempts_qty = int(config_obj.search_read(
this is old api. Please switch to browse and record object

2017-05-04 19:25 UTC, lasley commented on auth_brute_force/controllers/controllers.py
> +            config_obj = registry(request.session.db)['ir.config_parameter']
Switch all registry to env (`request.env`)

2017-05-04 19:25 UTC, lasley commented on auth_brute_force/controllers/controllers.py
> +            banned = banned_remote_obj.search(cursor, SUPERUSER_ID, [
Old api

2017-05-04 19:25 UTC, lasley commented on auth_brute_force/controllers/controllers.py
> +            attempt_obj.create(cursor, SUPERUSER_ID, {
Old api

2017-05-04 19:25 UTC, lasley commented on auth_brute_force/controllers/controllers.py
> +                    result and 'successfull' or 'failed'),
s/successfull/successful

2017-05-04 19:25 UTC, lasley commented on auth_brute_force/controllers/controllers.py
> +            cursor.commit()
Never commit transaction

2017-05-04 19:25 UTC, lasley commented on auth_brute_force/controllers/controllers.py
> +                attempts_qty = len(attempt_obj.search_last_failed(
Old api

2017-05-04 19:25 UTC, lasley commented on auth_brute_force/controllers/controllers.py
> +                    banned_remote_obj.create(cursor, SUPERUSER_ID, {
Old api

2017-05-04 19:25 UTC, lasley commented on auth_brute_force/controllers/controllers.py
> +                    cursor.commit()
Never commit

2017-05-04 19:25 UTC, lasley commented on auth_brute_force/controllers/controllers.py
> +            cursor.close()
Why?

2017-05-04 19:25 UTC, lasley commented on auth_brute_force/data/ir_config_parameter.xml
> +<openerp>
`<odoo noupdate="1">` & can remove data tag

2017-05-04 19:25 UTC, lasley commented on auth_brute_force/models/res_authentication_attempt.py
> +from openerp.tools.translate import _
This can be directly imported from `openerp` in the above line

2017-05-04 19:25 UTC, lasley commented on auth_brute_force/models/res_authentication_attempt.py
> +        ('successfull', _('Successfull')),
s/successfull/successful

2017-05-04 19:25 UTC, lasley commented on auth_brute_force/models/res_banned_remote.py
> +import json
Alphabetize imports

2017-05-04 19:25 UTC, lasley commented on auth_brute_force/models/res_authentication_attempt.py
> +from openerp import models, fields, api
Alphabetize imports

2017-05-04 19:25 UTC, lasley commented on auth_brute_force/models/res_banned_remote.py
> +        string='Ban Date', required=True, default=_default_ban_date)
`default=lambda s: s._default_ban_date()`

2017-05-04 19:25 UTC, lasley commented on auth_brute_force/security/ir_model_access.yml
> +- !record {model: ir.model.access, id: access_res_authentication_attempt_all}:
This should be moved to an `ir.model.access.csv` instead

2017-05-04 19:25 UTC, lasley commented on auth_brute_force/views/action.xml
> +<openerp>
`<odoo>` & can remove data tag

2017-05-04 19:25 UTC, lasley commented on auth_brute_force/views/menu.xml
> +<openerp>
`<odoo>` & can remove data tag

2017-05-04 19:25 UTC, lasley commented on auth_brute_force/views/view.xml
> +<openerp>
`<odoo>` & can remove data tag

2018-05-24 08:22 UTC, yajo commented
This became stale. Superseded by #1255.

2018-05-24 08:22 UTC, closed without merging