[ADD] red_october: Add support for Red October encryption
OCA/server-tools pull request #673
Opened 2016-12-25 07:44 UTC by lasley

This adds support for external encryption of files using [CloudFlare Red October](https://blog.cloudflare.com/red-october-cloudflares-open-source-implementation-of-the-two-man-rule/). It also allows for the creation of vaults and rights delegations to vaults for decryption.

At the moment, the encryption is intrinsically tied to the session user - using the (obviously insecure) plain text password that exists there. 

The plan is to provide a dropdown in the top right menu bar that will allow you to change your user context.

A field widget will also need to be created, replacing an unencrypted file with a password box for decryption instead. Enter the correct password, decrypted data shows where you need it.

It would be nice if some sort of temporary password storage could be implemented in order to circumvent the need for passwords to be entered every time around.

I also want to add some integrations for [create](https://laslabs.github.io/python-red-october/red_october.html#red_october.red_october.RedOctober.create_order), [view](https://laslabs.github.io/python-red-october/red_october.html#red_october.red_october.RedOctober.get_orders_outstanding), and [cancel](https://laslabs.github.io/python-red-october/red_october.html#red_october.red_october.RedOctober.cancel_order) of delegation orders. And probably some better tracking on the uses and expiries. 

The ReadMe for more info:

Red October Attachments
=======================

This module provides a ``red_october`` type to ``ir.attachment``, which provides
encryption and decryption services using a remote Red October instance.

Installation
============

A working Red October installation is required to use this module.

* Install the Python Red October library ``pip install git+https://github.com/LasLabs/python-red-october@feature/master/code-samples``

Configuration
=============

* Go to ``Settings => Crypto => Vaults`` to create and manage vaults.
  * Vault must be initialized in ``Action => Init Vault`` from vault form view.
* Manage crypto users in ``Settings => Crypto => Vaults``.

Usage
=====

* Create an Attachment of Type ``Red October``.
* Manage delegations in ``Settings => Crypto => Delegations``.

Developers looking to implement this functionality should use an ``ir.attachment``
field set to type ``red_october``.

Known issues / Roadmap
======================

* Decouple the Red October user passwords from Odoo passwords.
* Allow for multiple RedOctoberUsers per ResUser, with a selection controlled via the session.
* Allow for multiple RedOctoberVaults per ResCompany.
* Allow transferring files between vaults.
* If decrypt error, fail silently & instead hide the data. Need to handle in the encrypt too.
* Add delegation uses & delta to ``red.october.file.owner``.

2017-04-08 01:53 UTC, lasley commented
Alright I have finally finished my PoC, which actually works quite nicely. I'll update the original post above once I finalize things & update the ReadMe, but below is a summary of the additions.

A new encryption profiles menu has been added to the primary navigation bar:
![image](https://cloud.githubusercontent.com/assets/7397578/24824574/9e254648-1bc2-11e7-8eb2-f5206c3a7025.png)


By default, profiles are created on the fly using the session password. Users can change their password using the profiles menu.

![image](https://cloud.githubusercontent.com/assets/7397578/24824578/b8c5b848-1bc2-11e7-8e00-f19ffda54fc0.png)


Encryption is provided with the `.fields.RedOctober` field, which comes with a text widget. The user will be prompted for their password as soon as the field is present in a view, with non-blank data - or if they try to add a value that was previously blank.

![image](https://cloud.githubusercontent.com/assets/7397578/24824587/db91e61c-1bc2-11e7-944e-787d3c79aeeb.png)

Once the user enters their password, it will persist in the profile object until refresh. All fields that the user has access to decrypt will show the decrypted value. Inaccessible fields will be shown as so:

![image](https://cloud.githubusercontent.com/assets/7397578/24824599/1f99d2b6-1bc3-11e7-8d2a-3e0fb9bd3c49.png)

The best part is that the password never touches the database in any way. The Odoo server does have access to the password and the decrypted data for the duration of the request, but this is the same weakness that would be present in a transparent database encryption as well. 

I still have a lot of edge cases to weed out and the code is incredibly crappy, but it works. 

Anyone have thoughts on this implementation? cc @laslabs @hbrunn

2017-04-13 20:09 UTC, lasley commented
Alright my technical implementation is now done for the most part, I just need to add unit tests. I welcome anyone to try this - the ReadMe has now also been updated & the PR description reflects its contents.

2017-04-13 22:22 UTC, hbrunn requested changes
I want to make clear that I'm an interested security layman at best, so this is only an Odoo related review.
Red October is totally unknown to me, so I can't judge if any communication between the module and this service is problematic. (In my own mind, giving your secrets to 3rd parties is highly problematic, but you'll have thought about that before I guess)

2017-04-13 22:22 UTC, hbrunn commented on red_october/README.rst
> +* Audit Javascript XSS vulnerabilities
if you're interested, I was in contact with people from http://codeblau.de for a review of my encrypted fields approach. They still have a hefty price tag, but agreed to negotiate given they also appreciate open source projects
The founder of this company is mostly known for being the author of https://www.fefe.de/dietlibc

2017-04-13 22:22 UTC, hbrunn commented on red_october/controllers/main.py
> +        command = getattr(http.request.env['red.october.file'], command)
should we whitelist stuff here? Or at least forbid `command` to start with an underscore? I don't have an exploit at hand, but I feel this could be problematic, because you allow arbitrary functions here

2017-04-13 22:22 UTC, hbrunn commented on red_october/fields/red_october_char.py
> +            bin_size=False,
for performance, you might want to check if the current context has this not set. in this case, you don't need to create a new context, which will lose the caches

2017-04-13 22:22 UTC, hbrunn commented on red_october/fields/red_october_char.py
> +            record._cache[self.name] = data.get(record.id, False)
is it important to have `False` instead of `None`?

2017-04-13 22:22 UTC, hbrunn commented on red_october/models/ir_attachment.py
> +            if self.env.context.get('__crypt'):
is it security relevant that anyone can manipulate the context?

2017-04-13 22:22 UTC, hbrunn commented on red_october/models/red_october_delegation.py
> +        """ It runs a remote delegation & deactivates existing active locals.
i noticed this before, but now I speak up: In python, documentation tends to be in the active tense: `Run a remote delegation & deactivate existing active locals`

2017-04-13 22:22 UTC, hbrunn commented on red_october/models/red_october_delegation.py
> +        if self._context.get(self.CONTEXT_SKIP):
also here: I cannot judge the security implications, but anyone can set a context

2017-04-13 22:22 UTC, hbrunn commented on red_october/models/red_october_file.py
> +            if len(changed):
your don't need to test the length for a recordset: https://github.com/OCA/OCB/blob/10.0/odoo/models.py#L5062

2017-04-13 22:22 UTC, hbrunn commented on red_october/models/red_october_user.py
> +            if len(results) > 1:
you should rely on the implementation of truthyness of recordsets

2017-04-13 22:22 UTC, hbrunn commented on red_october/models/red_october_user.py
> +            if is_admin is not None and is_admin != record.is_admin:
can I use this to inject evil values in the cache?

2017-04-13 22:22 UTC, hbrunn commented on red_october/models/red_october_user.py
> +        setattr(request.session, self.SESSION_USER_ATTR, ro_user_id)
can I hijack another user's session with this?

2017-04-13 22:22 UTC, hbrunn commented on red_october/models/red_october_user.py
> +        ])
`self.mapped` might be simpler here

2017-04-13 22:22 UTC, hbrunn commented on red_october/models/res_company.py
> +        compute="_compute_default_red_october_id",
we have a different convention for that: https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#models

2017-04-13 22:39 UTC, lasley commented on red_october/fields/red_october_char.py
> +            record._cache[self.name] = data.get(record.id, False)
Mainly just that `False` seems to correspond with what Odoo typically puts as a blank field value. Bugs the hell out of me personally, so let me know if this isn't the case.

2017-04-13 22:42 UTC, lasley commented on red_october/models/ir_attachment.py
> +            if self.env.context.get('__crypt'):
It was! I refactored around this and forgot to remove the hook - good catch

2017-04-13 22:48 UTC, lasley commented on red_october/models/red_october_user.py
> +            if len(results) > 1:
This is a constraint, so we're testing for more than one. I think we're good in this instance?

2017-04-13 22:50 UTC, lasley commented on red_october/models/red_october_user.py
> +            if is_admin is not None and is_admin != record.is_admin:
Hmmmmm probably. I can refactor around this now that I wrote all the JS 👍

2017-04-13 22:52 UTC, lasley commented on red_october/models/red_october_user.py
> +        setattr(request.session, self.SESSION_USER_ATTR, ro_user_id)
Yes, but only in the sense that you would appear logged in as that user. You would still need to provide a decryption password into the UI - so no big deal.

The decryption password is stored in the browser memory due to the Odoo frame not actually changing as you navigate the backend. It is never stored in the session, although the user does default with the Odoo password from the session if they are not created through the Vault initialization. This weakness is then circumvented by changing the password via the Crypto Menu

2017-04-13 22:55 UTC, lasley commented on red_october/models/red_october_user.py
> +        ])
Interesting - how could I use `self.mapped` here? `self.filtered` perhaps?

General question on this - I assumed these methods first gathered all records, then filtered/mapped. Are they operating directly within the DB, before iterating the cursor?

2017-04-13 23:07 UTC, tedsalmon reviewed
I've left some comments for things I found in my functional tests :)

2017-04-13 23:07 UTC, tedsalmon commented on red_october/README.rst
> +    tab in the `res.users` form view
I think the indent here is causing some rendering issues in the README. This appears quoted in the Github view.

2017-04-13 23:07 UTC, tedsalmon commented on red_october/README.rst
> +    `Already Active` box.
I think the indent here is causing some rendering issues in the README. This appears quoted in the Github view.

2017-04-13 23:07 UTC, tedsalmon commented on red_october/README.rst
> +    exceeded
Indent.

2017-04-13 23:07 UTC, tedsalmon commented on red_october/wizards/red_october_vault_activate.py
> +        self.unlink()
I believe this is causing a bug where when initiating a new, inactive vault you get an Odoo Warning about missing records.

2017-04-13 23:08 UTC, lasley commented on red_october/wizards/red_october_vault_activate.py
> +        self.unlink()
Damn this was a hack to remove my ephemeral fields. I'll JS this too then

2017-04-13 23:12 UTC, lasley commented
@hbrunn - Thanks for the review! Most of the items fixed, will nail the outstanding soon.

Regarding Red October - I thought a lot about this, and my stance is that the external system actually provides a layer of protection that we would not otherwise have. We will assume that Red October itself is secure, because CloudFlare uses it and says it's secure. Taking the crypto out of it is huge IMO, and leave us with simple API interactions.

Now what's left to us is specifically watching where the password and decrypted data touch. Everything else is irrelevant, assuming that the connection between Odoo and Red October is also secure. This module does not provide a way to use a Red October server that is HTTP, so the least secure there would be unchecking the `Verify Cert` box in the Vault.

Here's my data architecture diagram of this. Most is obviously irrelevant, but the left hand side is valid in the context of this conversation. Data labelled as `2 - Confidential` (red) in the diagram is the password and decrypted data.

![system architecture flow](https://cloud.githubusercontent.com/assets/7397578/25027678/68cb49d4-2063-11e7-8963-92be0dae0ded.png)

One of the big things that's a killer for us in terms of security right now is Odoo's model  JS inheritance structure. This magic is actually going to work against us, because to be truly secure (IMO) we cannot allow a simple module installation to expose data that should be otherwise treated as confidential. 

I'm still playing with possible ways for this, but I think the ideal is the creation of a new decorator `@secure(2)`. The number sent as an arg to the decorator will be the amount of bases that can exist on the class. If the amount of bases exceeds allowed, we know we have inheritance & we should fail. This is manual and shitty though, so I'm totally open to some magical idea if you have one 🚀

2017-04-13 23:24 UTC, hbrunn commented on red_october/fields/red_october_char.py
> +            record._cache[self.name] = data.get(record.id, False)
just ask the field what its null value is: https://github.com/OCA/OCB/blob/10.0/odoo/fields.py#L767

2017-04-13 23:26 UTC, hbrunn commented on red_october/models/red_october_user.py
> +            if len(results) > 1:
right, you check for greater than one

2017-04-13 23:26 UTC, lasley commented on red_october/README.rst
> +* Audit Javascript XSS vulnerabilities
I'll keep this in mind - at the moment I'm not too worried, but an external audit will need to happen as we start scaling. Thanks!

2017-04-13 23:53 UTC, hbrunn commented
I pass the question for the magical idea on, because unfortunately, I don't have it. But there's a nice Metal song about California, if I expect your place of living right: https://www.youtube.com/watch?v=ILZ_lyZVyd8
For forbidding unwanted inheritance, I'd suggest passing down some token in the inheritance chain, and only functions validating it are actually run

2017-04-14 00:09 UTC, hbrunn commented on red_october/models/red_october_user.py
> +        ])
i think we could make odoo a lot faster by parsing `.mapped` and `.filtered` and emit sql for it. but as things are currently, it's getting stuff and just then filter it

2017-04-14 00:11 UTC, hbrunn commented on red_october/models/red_october_user.py
> +        ])
if not clear: all model functions operate on local

2017-04-14 15:43 UTC, lasley commented
I'm right next door to California, so close enough! And that metal sent me into a nice Spotify rabbit hole, so I thank you for that 🎉 

Interesting idea with the token - basically a CSRF for classes. I'll run with that, thanks!

2017-12-18 04:09 UTC, chris001 commented
@lasley 
This looks really nice.  Would be great to have on 11.0.  I notice both Travis build and Runbot build failed, but this was 7 months ago, and the build log isn't available now.  Any updates?

2017-12-18 16:39 UTC, lasley commented
@chris001 - I haven't touched this for a few months. At the moment, the module is fully functional though outside of some usability things - primarily with decryption rights delegation. I amend/pushed so that you can functionally test if you'd like.

This is a personal project of mine and doesn't have any specific customer funding, so the progress is slow going - particularly given the feature complexity. I hoped to have it done by end of this year, but we've been particularly busy as of late.

2022-06-05 12:29 UTC, closed without merging