[IMP] Update LetsEncrypt and improve readme
OCA/server-tools pull request #682
Opened 2016-12-30 08:33 UTC by kenneth-vkd

I have updated the readme.rst file to be a little more helpful for users that are not technically experienced in nginx configuration as well as fixed issues that prevented Odoo 10 form generating a LetsEncrypt certificate.

2016-12-30 11:23 UTC, hbrunn requested changes

2016-12-30 11:23 UTC, hbrunn commented on letsencrypt/README.rst
> +            if ($request_uri ~ ^/pos/web/) {
why this?

2016-12-30 11:23 UTC, hbrunn commented on letsencrypt/README.rst
> +A complete configuration file could look like this::
a user who needs the below probably also needs instructions what to change where. You probably should add comments about that if you want this to be foolproof

2016-12-30 11:23 UTC, hbrunn commented on letsencrypt/__manifest__.py
> +    "version": "1.0.0",
the version should be `10.0.1.0.0`

2016-12-30 11:23 UTC, hbrunn commented on letsencrypt/__manifest__.py
> +              "VK Data ApS,"
contributor I'd understand, but author seems a bit over the top to me

2017-01-01 01:09 UTC, lasley commented on letsencrypt/README.rst
> +            ssl on;
These should match current Mozilla recommended settings - https://wiki.mozilla.org/Security/Server_Side_TLS

There's a generator here - https://mozilla.github.io/server-side-tls/ssl-config-generator/

Might also want to add a comment with that link.

2017-03-01 23:11 UTC, NL66278 requested changes
Glad this will be moved to 10.0. Please take into account remarks by hbrunn and lasley, and then it will look good to me.

2018-01-31 11:54 UTC, yvaucher commented
I close this as no activity since 2017-3-2

2018-01-31 11:54 UTC, closed without merging