ADD module active_previous_actived_cron
OCA/server-tools pull request #685
Opened 2017-01-03 17:49 UTC by bealdav

Use case:

Your ERP is in production, and you have an issue.
You should stop the automatical tasks to understand what is the real problem.

* Install this module: all tasks (crons) are now inactive
* Fix the issue
* Uninstall this module: all tasks previously active, and only them, are now active.

When the production is repaired, you may forget to active one or more crons.
Some of them may run important features.

With this module, you can't forget anymore.

2017-01-03 17:58 UTC, bealdav commented
I don't know how to improve codecov.
How to test unit install and install of modules ?

2017-01-03 18:14 UTC, lasley commented on active_previous_actived_cron/models/ir_cron.py
> +            [('active_old', '=', True)])
@bealdav - couldn't you just create a cron matching this record, then test the writes? Running the method will trigger the super, which will 🍏  that too

2017-01-03 20:19 UTC, bealdav commented on active_previous_actived_cron/models/ir_cron.py
> +            [('active_old', '=', True)])
thanks @lasley

2017-01-03 20:28 UTC, bealdav commented
I'm open to rename my module if any good idea

2017-01-03 21:16 UTC, hbrunn requested changes
I must admit I don't see the use case for this module, but you wouldn't have written it without one, so I don't mind.

But I think there's a conceptual problem: Installing/uninstalling a module causes a registry reload, which can impact debugging to the degree of masking the problem you currently want to debug. Why don't you provide a means to flip crons on and off via some button on some `ir.config.settings` or the like? Then you save the registry reload.

And as reminder to turn on the crons again, how about implementing `ir.needaction_mixin`?

2017-01-03 21:16 UTC, hbrunn commented on active_previous_actived_cron/models/ir_cron.py
> +        if crons:
I don't think this check is necessary, a `write` on an empty recordset is basically a noop

2017-01-03 21:16 UTC, hbrunn commented on active_previous_actived_cron/models/ir_cron.py
> +        if crons:
same here

2017-01-03 21:16 UTC, hbrunn commented on active_previous_actived_cron/tests/test_reactive_cron.py
> +        self.assertEqual(len(crons), 0, "All crons should be inactive")
`assertFalse` is a bit more concise and (at least to me) simpler to read

2017-01-03 21:16 UTC, hbrunn commented on active_previous_actived_cron/tests/test_reactive_cron.py
> +        self.assertTrue(cron in [x for x in crons],
this is not v6 any more, you can (and should) use [recordset](https://github.com/OCA/OCB/blob/10.0/odoo/models.py#L5058) [arithmetics](https://github.com/OCA/OCB/blob/10.0/odoo/models.py#L5095)

2017-01-03 21:16 UTC, hbrunn commented on active_previous_actived_cron/__manifest__.py
> +    'data': [
delete empty key

2017-01-03 21:17 UTC, hbrunn commented
@pedrobaeza probably has two ideas about the rename!

2017-01-03 23:22 UTC, pedrobaeza commented
hehe, now that I'm the renamer guy, I suggest to use `cron_activation_persistent` or `cron_activation_changeset`, depending on the final approach you give to the module. I also suggest to make something like a changeset: put a name to an specific cron activation status, having the possibilities to save as much as you want. Include two by default: all activated and all deactivated. Having a button for enabling a certain cron changeset will do the rest, including your use case.

2017-01-04 09:19 UTC, legalsylvain requested changes
Hi @bealdav, 

Thanks for this contribution.

Point 1. @hbrunn  said
> Why don't you provide a means to flip crons on and off via some button on some ir.config.settings or the like?

+1. An ir.config.parameter, managed by an ir.config.settings should be better.

Point 2. One of the base cron is autovacuum_job. I guess it's not very good to disable it : 

- it is the only one to be enabled, by default on each installation
- it is the only one that is not set as noupdate="1", that supposes that it should be allways active. (or will be reactivated at each update)

What I see, if you're agree :

* In your class module add a list : 

        _KEEP_ALIVE_MODULE = [
            'base.autovacuum_job',
        ]

* filter on your search, with crons which ids are not in the list defined.

what do you think ?

Point 3. Possible improvment (not a blocking point). When I restore a production database, I'd like to be sure that all cron are disabled by default, specially because crons send mails, or communicate with third apps. So in a second time, we could image that if a key is present on the config file, when we run the odoo instance, crons are disabled too. (my personal use case, I don't know if other OCA members should be interested too).

Point 4. no PoV about the name of the module.

Kind regards.

2017-01-04 10:43 UTC, bealdav commented
Hi all, 

Point 1:
OK, no needs to uninstall to switch back to the previous cron state.
but I prefer to have button on settings page than ir.config.settings, what do you think ?

Point 2:
Why not, Ok

Point 3:
I'm ok with you, it could be interesting for dev purpose. Which key name ?

2017-01-04 11:10 UTC, legalsylvain commented
Point 1 : The installation of this module should not disable the cron too, right ?

point 3 : "disable_cron_tasks" ? I let

2017-01-04 11:13 UTC, bealdav commented
> he installation of this module should not disable the cron too

Yes

2017-01-04 11:45 UTC, bealdav commented
Thanks for your suggestion, I will rework my PR

2017-01-04 11:46 UTC, pedrobaeza commented
@bealdav, have you seen my suggestions?

2017-01-04 11:47 UTC, bealdav commented
yes, but no sure to have completely understood them except if they are in the other proposal

2017-01-04 11:55 UTC, pedrobaeza commented
OK, then nevermind

2017-01-04 17:42 UTC, bealdav commented on active_previous_actived_cron/__manifest__.py
> +    'data': [
I'll add a file for UI

2017-01-04 17:42 UTC, bealdav commented
ping @legalsylvain

2017-01-04 17:54 UTC, bealdav commented on active_previous_actived_cron/models/ir_cron.py
> +                self._inactive_crons()
needs to decide the behavior here according cron is in KEEP_ALIVE_CRONS or not

2017-03-02 11:40 UTC, legalsylvain requested changes
I reviewed and propose some changes. Adding a new ir.config;parameter that has to be switch by UI. 'disable_cron_task'.

call me if it's not clear.

2017-03-02 11:40 UTC, legalsylvain commented on active_previous_actived_cron/models/ir_cron.py
> +        crons = self.search([('id', 'not in', alive_crons)])
& ('active', '=', True)

2017-03-02 11:40 UTC, legalsylvain commented on active_previous_actived_cron/models/ir_cron.py
> +
replace line 28-> 30 by : 
    
    if crons:
        vals = {'active': False, 'active_old': True}
        crons.write(vals)
        self.env['ir.config_parameter'].set_param(PARAM, True)

2017-03-02 11:40 UTC, legalsylvain commented on active_previous_actived_cron/models/ir_cron.py
> +PARAM = 'disable_cron_tasks'
rename into CRON_TASK_DISABLED = 'cron_task_disabled'

2017-03-02 11:40 UTC, legalsylvain commented on active_previous_actived_cron/models/ir_cron.py
> +        self.env['ir.config_parameter'].set_param(PARAM, False)
replace line 35 + 36 by : 

    if crons:
        crons.write({'active': True})
        crons.write(vals)
        self.env['ir.config_parameter'].set_param(CRON_TASK_DISABLED, False)

2017-03-02 11:40 UTC, legalsylvain commented on active_previous_actived_cron/models/ir_cron.py
> +PARAM = 'disable_cron_tasks'
Add a new line DISABLE_CRON_TASK = 'disable_cron_task'

2017-03-02 11:40 UTC, legalsylvain commented on active_previous_actived_cron/models/ir_cron.py
> +            model_name, method_name, args, job_id)
replace full function by 

    to_disable =  config.get(DISABLE_CRON_TASK) or\
        self.env['ir.config_parameter'].get_param(DISABLE_CRON_TASK)
    disabled = self.env['ir.config_parameter'].get_param(PARAM)

    if to_disable and not disabled:
        self._inactive_crons()
    if not to_disable and disabled:
        self._active_previous_crons()
    return super(IrCron, self)._callback(
        model_name, method_name, args, job_id)

2017-03-02 11:40 UTC, legalsylvain commented on active_previous_actived_cron/README.rst
> +* Click on button in General Settings : all tasks (crons) are now inactive
Add : 
1. by UI, on a running instance ....

2017-03-02 11:40 UTC, legalsylvain commented on active_previous_actived_cron/README.rst
> +
2. By config parameter, adding a key 'disable_cron_task' = True. ....

2018-01-31 11:55 UTC, yvaucher commented
@bealdav are you willing to work on this ?

2022-05-08 13:51 UTC, closed without merging