8 password security backport
OCA/server-tools pull request #691
Opened 2017-01-09 16:17 UTC by bealdav

2017-01-09 17:29 UTC, bealdav commented
ping @lasley

2017-01-09 17:39 UTC, lasley commented
Hooray! I'll review today 😄

2017-01-10 00:01 UTC, lasley requested changes
Nice thanks @bealdav - one minor comment, plus akretion#9 to fix #674

2017-01-10 00:01 UTC, lasley commented on password_security/__openerp__.py
> +    'version': '8.0.1.0.3',
8.0.1.0.0

2017-01-10 17:44 UTC, lasley approved these changes

2017-01-11 01:06 UTC, moylop260 approved these changes

2017-01-11 09:06 UTC, mourad-ehm commented
:+1:

2017-01-11 11:09 UTC, sylvainc commented
Hello,

Thanks, :+1: (code review)

2017-01-11 15:13 UTC, merged