[WIP] 8.0 database cleanup create indexes
OCA/server-tools pull request #740
Opened 2017-02-17 15:51 UTC by NL66278

Backport of 9.0 version done by @hbrunn. In process of testing.

2017-02-17 17:27 UTC, hbrunn commented
it just occurs to me that I used the occasion of migrating to 9.0 to rebuild all views to use primary views in order to avoid a lot of code duplication. So either you can repeat all the code from one of the other views, or partially cherry pick https://github.com/OCA/server-tools/commit/ece76e72a30f67c5b34d7035c25394a3dc09a5a4 where I did these changes.

2017-02-20 11:56 UTC, NL66278 commented on database_cleanup/views/menu.xml
> +        </record>
Is this not missing the parent_id element? This will create top level menu entry...

2017-02-20 14:57 UTC, hbrunn commented on database_cleanup/models/purge_menus.py
> +                    model_deleted(menu.action.res_model):
8 doesn't support the `in` operator on envs, but the registry does, which is accessible via `env.registry`

2017-02-20 16:26 UTC, NL66278 commented
@hbrunn  Now checking self.env.registry.

2017-02-22 09:37 UTC, hbrunn requested changes
a few misses about envs.

Generally, I think you try to do too much within one PR. This makes the diff very big and thus review inconvenient. As a consequence, the chances to get this merged decrease I fear.

2017-02-22 09:37 UTC, hbrunn commented on database_cleanup/models/purge_models.py
> +            this.id for this in self if this.model in self.env
+ `.registry`

2017-02-22 09:37 UTC, hbrunn commented on database_cleanup/models/purge_modules.py
> +                if not field.exists() or field.model not in self.env:
+ `.registry`

2017-02-22 09:37 UTC, hbrunn commented on database_cleanup/models/purge_modules.py
> +            if this.model not in self.env:
+ `.registry`

2017-02-22 10:02 UTC, hbrunn commented
I just fixed a nasty bug in the 9.0 branch, you should cherry pick https://github.com/OCA/server-tools/pull/736/commits/f854f7e5377c9a9a226a6ad2a699afc83a0d2e0c

2017-02-22 10:49 UTC, NL66278 commented
@hbrunn Cherry-pick done and .registry added. Large amount of changes is due to fact that it turned out to be a lot more easy and reliable to backport all 9.0 changes to 8.0 then to add them in piece by piece (as I tried ad first). As directory names where changed to standard models and views (with the plural 's')  in 9.0, this makes for a large diff. But review will be easy if just comparing 9.0 and 8.0 branch and check for needed changes to make everything work on 8.0.

2019-08-14 07:59 UTC, hbrunn commented
@NL66278 please rebase or if you don't have time, I can take over this PR

2019-08-14 08:16 UTC, NL66278 commented
@hbrunn Rebase done

2019-08-14 08:33 UTC, hbrunn approved these changes

2019-08-14 08:37 UTC, hbrunn commented
thanks! now if at least one @Therp/core person approves this we can merge

2019-08-14 08:39 UTC, hbrunn commented
ping @Therp/core

2022-06-26 12:30 UTC, closed without merging