[10.0][FIX] Crash in base_user_role when role_id is not set on res.users.role.line
OCA/server-tools pull request #857
Opened 2017-06-12 21:16 UTC by alexis-via

To get the crash:
1) login as admin
2) Edit the "demo" user
3) In the Role tab, add a new line and leave the Role field empty
You get this crash:

```
2017-06-12 21:10:25,105 6068 INFO o0_test1 odoo.sql_db: bad query:  INSERT INTO res_groups_users_rel (uid, gid)
                        (SELECT a, b FROM unnest(ARRAY[5]) AS a, unnest(ARRAY[32, 1, false, 65, 71, 47, 26]) AS b)
                        EXCEPT (SELECT uid, gid FROM res_groups_users_rel WHERE uid IN (5))
                    
2017-06-12 21:10:25,106 6068 ERROR o0_test1 odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/alexis/new_boite/dev/odoo0/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/alexis/new_boite/dev/odoo0/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/home/alexis/new_boite/dev/odoo0/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo0/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo0/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/alexis/new_boite/dev/odoo0/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/home/alexis/new_boite/dev/odoo0/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/home/alexis/new_boite/dev/odoo0/addons/web/controllers/main.py", line 885, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/alexis/new_boite/dev/odoo0/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/alexis/new_boite/dev/odoo0/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/alexis/new_boite/dev/odoo0/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo0/addons/hr/models/res_users.py", line 17, in write
    result = super(User, self).write(vals)
  File "/home/alexis/new_boite/dev/odoo0/addons/mail/models/res_users.py", line 56, in write
    write_res = super(Users, self).write(vals)
  File "/home/alexis/new_boite/dev/server-tools0/base_user_role/models/user.py", line 31, in write
    self.sudo().set_groups_from_roles()
  File "/home/alexis/new_boite/dev/server-tools0/base_user_role/models/user.py", line 54, in set_groups_from_roles
    super(ResUsers, user).write(vals)
  File "/home/alexis/new_boite/dev/odoo0/odoo/addons/base/res/res_users.py", line 802, in write
    res = super(UsersView, self).write(values)
  File "/home/alexis/new_boite/dev/odoo0/odoo/addons/base/res/res_users.py", line 640, in write
    res = super(UsersImplied, self).write(values)
  File "/home/alexis/new_boite/dev/odoo0/odoo/addons/base/res/res_users.py", line 355, in write
    res = super(Users, self).write(values)
  File "/home/alexis/new_boite/dev/odoo0/odoo/models.py", line 3564, in write
    self._write(old_vals)
  File "/home/alexis/new_boite/dev/odoo0/odoo/models.py", line 3687, in _write
    field.write(self.with_context(rel_context), vals[name])
  File "/home/alexis/new_boite/dev/odoo0/odoo/fields.py", line 2402, in write
    link(act[2])
  File "/home/alexis/new_boite/dev/odoo0/odoo/fields.py", line 2367, in link
    cr.execute(query, (records.ids, list(sub_ids), tuple(records.ids)))
  File "/home/alexis/new_boite/dev/odoo0/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo0/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
ProgrammingError: ARRAY types integer and boolean cannot be matched
LINE 2: ...b FROM unnest(ARRAY[5]) AS a, unnest(ARRAY[32, 1, false, 65,...
                                                             ^
```

2017-06-12 21:36 UTC, sylvain-garancher commented on base_user_role/models/user.py
>              group_ids = list(set(group_ids))    # Remove duplicates IDs
I think the method could be refactored to use more new-API magic.

Untested proposal (written directly in this comment):
```python
    @api.multi
    def set_groups_from_roles(self):
        """Set (replace) the groups following the roles defined on users.
        If no role is defined on the user, its groups are let untouched.
        """
        for user in self.filtered('role_line_ids'):
            role_lines = user.role_line_ids.filtered('is_enabled')
            groups = (
                role_lines.mapped('role_id.group_id') +
                role_lines.mapped('role_id.implied_ids')
            )
            super(ResUsers, user).write({
                'groups_id': [(6, 0, groups.ids)],
            })
        return True
```

2017-06-13 07:53 UTC, yajo requested changes
A unit test for the case you mentioned would be awesome.

2017-06-13 07:53 UTC, Yajo commented on base_user_role/views/user.xml
> +                        <field name="role_id" required="1"/>
Can't you just add this in the model? It should be enough fix, right?

2017-06-13 08:03 UTC, sebalix commented on base_user_role/views/user.xml
> +                        <field name="role_id" required="1"/>
I agree, `role_id` should be required in `res.users.role.line` (and `user_id` too I think, with `ondelete='cascade'` as well).

2017-06-14 07:25 UTC, alexis-via commented on base_user_role/views/user.xml
> +                        <field name="role_id" required="1"/>
Feel free to propose a PR to this PR to improve it if you wish. This PR was just a quick for to avoid the crash, nothing more.

2017-06-14 11:31 UTC, adrienpeiffer approved these changes
:+1: Thanks for the fix !

2017-07-12 08:01 UTC, MiquelRForgeFlow approved these changes

2017-07-12 08:05 UTC, sebalix approved these changes

2017-07-12 09:40 UTC, merged