[MIG] auth_brute_force: Migration to 10.0
OCA/server-tools pull request #877
Opened 2017-06-26 14:29 UTC by chienandalu

Tracks Authentication Attempts and Prevents Brute-force Attacks
===============================================================

This module registers each request done by users trying to authenticate into
Odoo. If the authentication fails, a counter is increased for the given remote
IP. After a defined number of attempts, Odoo will ban the remote IP and
ignore new requests.

cc @Tecnativa

2017-06-28 17:31 UTC, pedrobaeza requested changes
Tried also on runbot with a non correct behavior:

* Login n times until I reach the limit.
* On last attempt, it gets me to an incorrect "Internal Server Error", and no banned remote is written.
* Then, I'm able to login again with correct credentials.

2017-06-28 17:31 UTC, pedrobaeza commented on auth_brute_force/README.rst
> +Attempt 1 / 10.
Why do you remove indentation? This provokes an incorrect RST syntax. It was correct as it was.

2017-06-28 17:31 UTC, pedrobaeza commented on auth_brute_force/README.rst
> +The ID used to identify a remote request is the IP provided in the request
Put `*` and indent the rest of the lines.

2017-06-28 17:31 UTC, pedrobaeza commented on auth_brute_force/README.rst
> +all the request will be have the value '127.0.0.1' for the REMOTE_ADDR key;
Indent the line

2017-06-28 17:31 UTC, pedrobaeza commented on auth_brute_force/README.rst
> +banned, all the other users will be banned too;
Indent the line

2017-06-28 17:31 UTC, pedrobaeza commented on auth_brute_force/__manifest__.py
> +    'author': "GRAP,Odoo Community Association (OCA)",
Add Tecnativa here

2017-06-28 17:31 UTC, pedrobaeza commented on auth_brute_force/data/ir_config_parameter.xml
> +<odoo>
Put directly `<odoo noupdate="1">`

2017-06-28 17:33 UTC, pedrobaeza commented on auth_brute_force/controllers/controllers.py
> +                        banned_remote_obj.create(cursor, SUPERUSER_ID, {
You haven't converted this to new API (`banned_remote_obj.sudo().create({ ... })`)

2017-06-28 17:48 UTC, Garamotte requested changes

2017-06-28 17:48 UTC, sylvain-garancher commented on auth_brute_force/controllers/controllers.py
> +# -*- coding: utf-8 -*-
This file is usually named `main.py`.

2017-06-28 17:48 UTC, sylvain-garancher commented on auth_brute_force/controllers/controllers.py
> +                max_attempts_qty = int(config_obj.search_read(
Use `config_obj.get_param('auth_brute_force.max_attempt_qty')` instead of `search_read`.

2017-06-28 17:48 UTC, sylvain-garancher commented on auth_brute_force/controllers/controllers.py
> +                cursor.commit()
There is a commit just after the next instruction, is this commit really needed ?

2017-06-28 17:48 UTC, sylvain-garancher commented on auth_brute_force/data/ir_config_parameter.xml
> +    <data noupdate="1">
Remove the `data` node and include the `noupdate` attribute in the `odoo` node.

2017-06-28 17:48 UTC, sylvain-garancher commented on auth_brute_force/models/res_banned_remote.py
> +        string='Ban Date', required=True, default=_default_ban_date)
`default=fields.Datetime.now`.

2017-06-28 17:48 UTC, sylvain-garancher commented on auth_brute_force/models/res_banned_remote.py
> +            item.attempt_ids = attempt_obj.search_last_failed(item.remote).ids
You can remove the trailing `.ids`, Odoo allows you to assign a recordset.

2017-06-29 10:59 UTC, chienandalu commented on auth_brute_force/README.rst
> +Attempt 1 / 10.
Seem like my editor tried somehow to re-indent it...

2017-06-29 11:04 UTC, chienandalu commented
@pedrobaeza @sylvain-garancher I coded your suggestions and tested functionally in local.

2017-06-29 11:05 UTC, chienandalu commented on auth_brute_force/controllers/controllers.py
> +                cursor.commit()
Yes. It seems that it's not neccesary.

2017-06-29 12:42 UTC, pedrobaeza approved these changes

2017-06-30 07:54 UTC, Garamotte approved these changes

2017-07-29 12:53 UTC, merged