[ADD] Module which enable tracking history during import.
OCA/server-tools pull request #907
Opened 2017-07-24 11:14 UTC by benwillig

2017-07-25 07:11 UTC, yajo requested changes

2017-07-25 07:11 UTC, Yajo commented on base_import_default_enable_tracking/static/src/xml/base_import.xml
> +            <input type="checkbox" id="oe_import_tracking" checked="true"/>
Valid HTML is `checked=""` or `checked="checked"`

2017-07-25 07:11 UTC, Yajo commented on base_import_default_enable_tracking/static/src/xml/base_import.xml
> +        <t t-jquery="input#oe_import_tracking" t-operation="replace">
Use `t-operation="attributes"`

2017-07-25 07:11 UTC, Yajo commented on base_import_default_enable_tracking/__manifest__.py
> +    ],
Remove unneeded empty things.

2017-07-25 09:02 UTC, benwillig commented
@Yajo I updated my code. Thanks for the review.

2017-07-25 09:20 UTC, mreficent commented on base_import_default_enable_tracking/__manifest__.py
> +    'website': 'https://www.acsone.eu',
`https://github.com/OCA/server-tools`

2017-07-25 09:20 UTC, mreficent commented on base_import_default_enable_tracking/README.rst
> +To install this module, you need click on install button.
You can delete installation and configuration sections

2017-07-25 10:29 UTC, Yajo commented on base_import_default_enable_tracking/__manifest__.py
> +    'website': 'https://www.acsone.eu',
No problem on letting their URL, they were the original authors.

2017-07-25 10:30 UTC, yajo approved these changes

2017-07-25 10:38 UTC, mreficent commented on base_import_default_enable_tracking/__manifest__.py
> +    'website': 'https://www.acsone.eu',
That's why I didn't do the "request changes"

2017-07-25 12:46 UTC, atchuthan approved these changes
code review :+1:

2017-07-25 12:46 UTC, atchuthan commented on base_import_default_enable_tracking/static/src/xml/base_import.xml
> +</templates>
empty line after `</template>`

2017-08-16 12:56 UTC, dreispt commented on base_import_default_enable_tracking/README.rst
> +This modules simply enables history tracking when doing an import.
This is a feature that for some reason was removed from the UI, right?
Any chance that it is is an upstream bug?

2017-08-16 13:03 UTC, sbidoul commented on base_import_default_enable_tracking/__manifest__.py
> +    'website': 'https://www.acsone.eu',
Prefer https://github.com/OCA/server-tools, see also https://github.com/OCA/maintainer-tools/pull/276

2017-08-16 15:05 UTC, benwillig commented on base_import_default_enable_tracking/README.rst
> +This modules simply enables history tracking when doing an import.
This feature still exists but it's only available in debug mode. So it's not possible for a simple user to enable tracking before doing an import. If you install this module, tracking will always be enabled, and only a user who is in debug mode will be able to disable it.

2017-08-16 15:07 UTC, dreispt commented on base_import_default_enable_tracking/README.rst
> +This modules simply enables history tracking when doing an import.
OK

2017-08-16 15:07 UTC, dreispt approved these changes

2017-08-16 15:08 UTC, merged