[8.0] Add module export_sql_mail
OCA/server-tools pull request #925
Opened 2017-08-04 12:13 UTC by florian-dacosta

The module depends on sql_export and allow to send the result files from the queries by mail to a list of users.
There is the possibility to receive the mail only if the query is not empty, so it may be used to monitor some key datas.

2017-11-23 11:46 UTC, florian-dacosta commented
@bealdav @aheficent

2017-11-23 18:08 UTC, bealdav requested changes
Except signaled typo, LGTM

2017-11-23 18:08 UTC, bealdav commented on sql_export_mail/__openerp__.py
> +
Please a shorter header

2017-11-23 18:08 UTC, bealdav commented on sql_export_mail/models/sql_export.py
> +
shorter header please

2017-11-23 18:08 UTC, bealdav commented on sql_export_mail/models/sql_export.py
> +        'user_id',
The 3 args above are useless, I think, default generated ones  are sufficient

idem in the m2m below

2017-11-23 18:08 UTC, bealdav commented on sql_export_mail/models/sql_export.py
> +    def send_mail(self, params=None):
not blocking, but you can use this lib https://github.com/OCA/oca-decorators to avoid deprectaed @api.one

2017-11-23 22:40 UTC, florian-dacosta commented on sql_export_mail/models/sql_export.py
> +    def send_mail(self, params=None):
I thought it wasn't deprecated anymore, my bad.
Anyway, the api.one was useless in this case, I juste replaced by api.multi

2017-11-23 22:42 UTC, florian-dacosta commented on sql_export_mail/models/sql_export.py
> +        'user_id',
Indeed, theses 3 args are not very useful, changing it would break things for customers already using it though, so I would prefer let it this way.

2017-11-23 23:21 UTC, bealdav approved these changes

2017-11-24 02:54 UTC, andhit-r approved these changes

2019-09-02 10:42 UTC, closed without merging